### ISSUE TITLE
UAZ Door Vertex Stretching

### ISSUE THREAD

**Issue by BUB1312** [RadianSimulations/ghpc-feedback#101]
![image](https://user-images.githubusercontent.com/102687694/189522946-8a378940-ad34-464d-9398-d317d6499eb8.png)

![image](https://user-images.githubusercontent.com/102687694/189522936-778caa24-f090-49a5-bce9-7d1c5a840e68.png)

Images above are for the issue whenever the jeep flips and gets disabled the door that opens appears to still have an attachment point which pulls the texture.

**Comment by Waffle1434** [comment]
Potential skeleton skinning issue

**Comment by blake-bracerstudios** [comment]
Fixed.
