### ISSUE TITLE
Campaign NATO - Recon in Force only Bradleys

### ISSUE THREAD

**Issue by Stahl230** [RadianSimulations/ghpc-feedback#103]
**Describe the bug**

During NATO campaign there are recon in force mission. Mission screen is showing:
Friendly Forces (US Army)
Tank: M1IP
IFV: Bradley
APC: M113

No matter what forces are shown, recon in force is always 2-3 Bradleys. No other tanks or equipment availibe. 

**To Reproduce**
1. Campaign
2. look for a recon in force Mission
3. Start

**Expected Behavior**

Units as promised

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20220830

**Comment by rossmum** [comment]
Can confirm I've been getting 2x sections of 2 M2s no matter what the mission says I should actually have. I don't remember offhand which of the recce in force missions do it - I think one of them has always just given you a single section.

It was all Bradleys?
_Always has been._

**Comment by blake-bracerstudios** [comment]
Randomization has been adjusted in later updates. Closing this issue for now.
