### ISSUE TITLE
Graf Range Moving Issue

### ISSUE THREAD

**Issue by 167Armor** [RadianSimulations/ghpc-feedback#105]
While moving in the M1IP in the Graf range the turret controls freeze.

Got to Graf and pull out of the stationary position and move down range and place in cruise control and attempt to move turret in the main gun site optics mode.

I expected to be able to shoot on the move and engage targets.

Windows 10
Game version 9448202
 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**Comment by JoshBusuito** [comment]
Not happening this way for anyone else. If you can show video proof (preferably with your control inputs overlaid on the screen), re-open and post here.
