### ISSUE TITLE
Main Gun sight slop

### ISSUE THREAD

**Issue by 167Armor** [RadianSimulations/ghpc-feedback#106]
As a former M1IP and M1A1 Tank Commander: The main gun view when traversing the turret shows lots of delay that is not realistic to the M1IP or other M1 Abrams variants. The lagging reticle is too much.  Should only be a slight drag and once the turret traverse stops it should catch up quickly and actually bounce back and forth once.

**Comment by JoshBusuito** [comment]
Dump your lead

**Comment by 167Armor** [comment]
Yes understand to dump lead.  Even if you don't the actual lagging of the reticle is not nearly as much as displayed in the game even if you yank the turret quickly it is not that much.


-----Original Message-----
