### ISSUE TITLE
Two possible quality of life improvements

### ISSUE THREAD

**Issue by IamBriOnGitHub** [RadianSimulations/ghpc-feedback#108]
**Describe the bug**

Sent here by Harry in Dicsord. 

This isn't really a bug, more like a couple of small "quality of life" suggestions. They are:

1. Add a user-enableable option to have music playing during After-Action Report somehow, or if you decide you feel strongly that adding music here would be an unconditional value-add, then just take that choice away from the user and add it. AAR is a great feature and exceedingly fun to use to replay what happened, but the audio completely dropping out is rather striking after the rather *intense* experience of gameplay. Maybe someday if it makes sense, even dedicated AAR music might be a nice touch.

2. When in unbuttoned TC view/exterior view, and zoomed in ("using binoculars"), is it a desired behavior to have the mouse sensitivity remain the same? For my part, I have found it is very sensitive when zoomed, which makes spotting targets difficult before my brain "downshifts" to adjust to the higher rate of tracking when zoomed. I think having some reduction in sensitivity to keep the field of view from swinging wildly might be nice to have, if this makes sense to you. Some games do this kind of adjustment when looking down a sniper scope, for example.

**To Reproduce**

Play game. Use binoculars as TC. Win/lose, go to AAR.

**Expected Behavior**

See above. :)

**Screenshots**

N/A

**Sources**

N/A

**Desktop (Please complete the following information):**

Windows 10
Game Version: First Steam Early Access build

**Additional context**

**Comment by JoshBusuito** [comment]
Closing as this issues page is intended for actual issues. Thank you for the feedback.
