### ISSUE TITLE
Moving Tracks in AAR, in Intrepid Invasion map

### ISSUE THREAD

**Issue by fritomontana** [RadianSimulations/ghpc-feedback#109]
**Describe the bug**

Tracks of tank move while viewing AAR on Intrepid Invasion map.

**To Reproduce**

Steps to reproduce the behaviour:

Play Intrepid Invasion
Battle
Go to AAR
Cycle through shots
View tank with moving tracks

**Expected Behaviour**

the tracks of the tank should be moving

**Screenshots**

https://youtu.be/dHRGbzmK2eY - private video of expected behaviour

**Sources**

No applicable sources.

**Desktop (Please complete the following information):**

OS: Windows 10
Game Version 20220830.1

**Comment by JoshBusuito** [comment]
Steps listed are not sufficient to cause such an issue

**Comment by blake-bracerstudios** [comment]
Closing this for now until more steps are added to reproduce this sufficiently.
