### ISSUE TITLE
Gun movement speed changes with FPS 

### ISSUE THREAD

**Issue by nord-kind** [RadianSimulations/ghpc-feedback#11]
**Describe the bug**
Gun movement speed changes with FPS instead of beeing only dependant on the mouse displacement.

**To Reproduce**
1. Start the game with on a machine that will struggle to run smoothly. 
2. Open mission with high performance requirements (like bold limit). Make sure your FPS will vary by a lot. You need to have the fps switch between smoothly and stuttering to experience the issue.
3. Try to contain a smooth equal movement with reticle via your mouse movement. (Hold RMB, move the mouse for a small distance and hold it in place). 
4. Notice how the movement speed of the gun is depending on the current FPS and not on the actual displacement of the mouse. 

**Expected behavior**
The expected behaviour would be that the gun movement is solely depending on the displacement of the mouse. Any FPS changes should not affect the gun movement. Only a movement of the mouse should have an impact on the gun movement speed.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Win 7

**Comment by JoshBusuito** [comment]
Issue identified and corrected in dev branch
