### ISSUE TITLE
Company attack seal 

### ISSUE THREAD

**Issue by Dooby333** [RadianSimulations/ghpc-feedback#115]
**Describe the bug**

Upon starting the mission "Company Attack Seal" in the PACT campaign, you spawn in with "vehicle" from the q menu stuck on screen and your mouse cursor is overlayed on the screen. Once you press escape "vehicle" from the q menu disappears but you are unable to interact with the game in any way. 

The vehicles spawn in and the orders text appears telling you to move to waypoint 1. Physics appear to be working but no vehicles will move, and you are unable to interact in any way with your vehicle. 

You can't look through the gunners sight or swap views in any way. The Vehicle is locked in place along with the rest of the NPC vehicles. You can't enter freecam view.

**To Reproduce**

1). Load Steam early access 20221088 and start a pact campaign, start new ones until "Company Attack Seal" is in the list of available missions.
2). Attempt to run Company Attack Seal and the bug should occur.
3). The mission works in the NATO campaign 

**Expected Behavior**

The mission would be expected to work as other missions do and not completely break

**Screenshots**

A short webm showing the bug in action, its not visible but im pressing pretty much every vehicle action key and nothing happens:

https://streamable.com/9dckru

The Log file from the session: https://www.dropbox.com/s/w2jzw3dge0cxeeq/Player.log?dl=0

**Sources**

It was revealed to me in a dream

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version: 20221088

**Additional context**

N/A

**Comment by blake-bracerstudios** [comment]
Fixed as of 20221030.
