### ISSUE TITLE
Crash to Desktop, Raid mission

### ISSUE THREAD

**Issue by Kingman1828** [RadianSimulations/ghpc-feedback#116]
Hey started a raid campaign mission and after about two seconds in game I crashed to desktop 
Specs:
OS: Windows 10 64Bit
CPU: AMD Ryzen 5 5600X 
GPU: Nvidia 3080ti 
RAM: 32GB DDR4
the game is installed on a 1TB M.2 SSD
Wish I could give more Info, Ill attach the player Log to the Report as well 
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/9781167/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/9781168/Player.log)

**Comment by JoeThe-Pirate** [comment]
Similar issue, PACT raid "Praying mantis" crashed to desktop several minutes in several minutes in with no apparent cause

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/9883168/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/9883169/Player.log)

**Comment by blake-bracerstudios** [comment]
Neither of the reported log incidents give a clear background into why the error would have occurred (hardware or exception related). If the problem persists, please post another issue with the logs and crash dumps. Dumps can be found at the path noted on the very last line of your player log.
