### ISSUE TITLE
Detached flying pin on M60A3

### ISSUE THREAD

**Issue by wallross** [RadianSimulations/ghpc-feedback#117]
**Describe the bug**

There's a flying, spinning pin on the M60A3 that is visible when driving, it appears whenever the vehicle's wheels are moving and exits the hull model where the drivers hatch is. It looksa to be rotating around the front left idler wheel.

**To Reproduce**

Driving around on the M60A3 at a slow to moderate speed, keep an eye around the drivers hatch for a flying object that looks like a pin of a sort.

**Expected Behavior**

No flying pin when the vehicle is in motion

**Screenshots**

Screenshots provided.
**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20221008

**Additional context**

![2022-10-19T172027](https://user-images.githubusercontent.com/91963536/196762411-a10e0dd4-c25c-403b-b3af-f14883f54110.png)
![2022-10-19T171926](https://user-images.githubusercontent.com/91963536/196762478-dbca4813-3f13-4bf5-a3ef-1b4286356c5f.png)

**Comment by blake-bracerstudios** [comment]
Not important.
