### ISSUE TITLE
BMP-1 convoy light masking issue

### ISSUE THREAD

**Issue by rossmum** [RadianSimulations/ghpc-feedback#118]
**Describe the bug**

Since patch 20221008, the mask for the convoy light tac number no longer appears when the light is switched off.

**To Reproduce**

1. Turn off the convoy light. Done.

**Expected Behavior**

The mask to still appear, so the outline of the numbers can be seen even when switched off.

**Screenshots**

Light on:
![image](https://user-images.githubusercontent.com/90238132/196995678-8b8b20fa-bcd3-4db1-ad76-2f58f767a5a4.png)

Light off:
![image](https://user-images.githubusercontent.com/90238132/196995713-319fdd20-e5fa-4ba1-a7db-3e21d285e579.png)

From a previous version of the game:
![image](https://user-images.githubusercontent.com/90238132/196996054-d4a069f4-91de-45d4-9b35-8e42648944eb.png)

**Sources**

N/A.

**Desktop (Please complete the following information):**

 - OS: W10 21H2
 - Game Version 20221008

**Comment by JoshBusuito** [comment]
Fixed in RadianSimulations/GHPC-vertical#996
