### ISSUE TITLE
Adjust controls: buttons inactive

### ISSUE THREAD

**Issue by NextTomShark** [RadianSimulations/ghpc-feedback#119]
When entering "adjust inputs"in the settings, all buttons are infunctional.
I can only get back to the settings menu by ESC.
Issue occurs both accessing the inputs through main menu or ingame. No adjustments or entries possible.

 - OS: Win10
 - Game Version 20221008

**Comment by blake-bracerstudios** [comment]
Closing as this has gone stale. Please recreate and post a video or image of the issue as it happens if you are able to reproduce it.
