### ISSUE TITLE
Mission load bug on Company Attack Seal

### ISSUE THREAD

**Issue by wallross** [RadianSimulations/ghpc-feedback#121]
**Describe the bug**
Unable to control vehicle or switch player vehicle in Company Attack Seal with T-55's

**To Reproduce**

1. Go to Redfor campaign with a Company Attack Seal mission with T-55's. Player vehicle info displays placeholder data.
![GHPC_UnuIyawcgS](https://user-images.githubusercontent.com/91963536/197315898-9e1b5ecd-3a4a-439c-a078-d008e44acd72.png)

**Expected Behavior**

Able to control and switch player vehicle

**Screenshots**

**Sources**

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version [20221008]

**Additional context**

**Comment by blake-bracerstudios** [comment]
Duplicate of #115 and fixed.
