### ISSUE TITLE
Absent M1/M1IP GAS armor hole

### ISSUE THREAD

**Issue by Dooby333** [RadianSimulations/ghpc-feedback#127]
**Describe the bug**
The M1 Abrams GAS has armor covering where the optic is visible on the model. The coaxial machine gun does not have this same armor, nor does the M60 T-72M, or T-55, which all have machine gun vulnerable optics.

**To Reproduce**

Fire on the M1/M1IP GAS optic port with HMG or autocannon AP
It is unable to penetrate as its covered by thick armor in the damage model
Fire on the coax port and it is able to go through the gap.

**Expected Behavior**

Autocannon and HMG fire should go through this spot like it does in other tanks like the T-55A, T-72M or M60A3

**Screenshots**
https://i.imgur.com/kuUKoxO.png)

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20221088

**Comment by JoshBusuito** [comment]
Not important enough to devote artist hours for fix
