### ISSUE TITLE
Update 20221030 - NATO Thermal Display Bands Appear Overlaid on Map When Switching to Map View

### ISSUE THREAD

**Issue by IamBriOnGitHub** [RadianSimulations/ghpc-feedback#133]
**Describe the bug**

On new update version (20221030), when switching directly to Map View from NATO thermal gunsight view, the bands from the thermal sight overlay on the map. When opening the map from the optical gunsight, no bands appear.

**To Reproduce**

1. In a NATO tank with thermal gunsight, enter thermal gunsight view
2. Click M to open map

**Expected Behavior**

Expected no thermal gunsight bands.

**Screenshots**
![M60 Thermal Display Lines on Map View](https://user-images.githubusercontent.com/113746715/199149297-e88d1633-daf5-4f16-a2b3-344969d070c2.png)
![M1 Thermal Display Lines on Map View](https://user-images.githubusercontent.com/113746715/199149315-4fc4a90e-d77e-401e-828e-064bc5dc1c5a.png)

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20221030
 - Video card: NVidia GTX 1650 Super
 - Monitor: LG brand, not sure the type. If needed, can figure it out though. Resolution 2560x1440

**Additional context**

Loving the new update. Keep up the good work! Thank you!!

**Comment by blake-bracerstudios** [comment]
Fixed as part of 20221218 release.
