### ISSUE TITLE
NATO Thermal Scanlines Will Make Flames De-render

### ISSUE THREAD

**Issue by Sharkslay12** [RadianSimulations/ghpc-feedback#134]
**Describe the bug**

When switching to different thermal zoom levels, flames will not render once the Scanline animation has finished.

**To Reproduce**

1. Go to 'Combat Team'.
2. Destroy any vehicle. 
3. Use thermal optics and change zoom levels while looking at the burning vehicle.

**Expected Behavior**

Flames would remain instead of flickering.

**Video**

https://user-images.githubusercontent.com/100807231/199211537-621de9a2-3936-48ba-b8e9-49d56e5233cf.mp4

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version: 20221030

**Additional context**

Video had to be compressed to upload here.

**Comment by HankoDobringer** [comment]
all fire VFX are placeholder, WNF on this

**Comment by blake-bracerstudios** [comment]
Closing as VFX has been noted to be placeholder and noted for future effects.
