### ISSUE TITLE
AI Bradleys make poor weapon choices

### ISSUE THREAD

**Issue by ComradeCheekiBreeki** [RadianSimulations/ghpc-feedback#136]
**Describe the bug**

M2 Bradley AI gunners will generally make poor weapon choices in regards to ammo type, targeting and which weapon to use. The most notable examples are misuse of shell type (using AP on soft targets and HE on some armored targets) and massive preference to use the main gun over TOW missiles, even when having no AP ammo against heavy vehicles that could easily knock the Bradley out in a single solid hit. This also may be an issue with the gunner AI in general, but their choice of target seems extremely weird and sometimes they will prioritize targets you can barely see that are difficult to hit and far away over ones that are very close and threatening.

**To Reproduce**

1. Launch any mission with Bradleys, preferably one with soft targets like *Replen Reaper*
2. Join a Bradley platoon and play out the mission, allowing the AI to fire frequently
3. Check the AAR to see your AI Bradley gunners have used almost no TOWs and wasted much of their main gun's ammunition doing very little useful damage

**Expected Behavior**

Bradley gunners should prioritize using the best weapon for the situation, including using TOWs as often as possible over the main gun when engaging heavy vehicles (~BMP-1 or heavier). Being a reconnaissance and support vehicle, they should also attempt to conserve as much ammunition as possible, not firing wildly into enemy formations and attempting to hold fire until they are in a good position or are being targeted. This includes using the correct ammo for the target, to avoid wasting HE on targets that it will do nothing to and avoid wasting AP on targets that it massively overpens.

**Screenshots**

![image](https://user-images.githubusercontent.com/10621041/200998617-2f69d390-837b-4462-8014-18e19154698c.png)
This was on the aforementioned *Replen Reaper* mission. As you can see, the Bradley gunners have decided to fire AP at this truck, and they end up wasting about 30 rounds of AP in total on just soft targets. This is extremely bad for this mission in particular as you have little AP ammo and must carefully pick your targets to emerge on top. The only other thing we had going for us, the element of surprise, was also ruined, as the gunners immediately opened fire on the frontal column of BMPs the moment they came into view, giving us no time to set up in a proper position or do any kind of reconnaissance. Some types of AI commands, like "Hold fire," "Return fire only," "Stealth mode," etc. would be very helpful in these situations.

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Win. 10
 - Game Version 20221030

**Comment by blake-bracerstudios** [comment]
AI improvements will happen as the game develops, and proper weapon selection will be one of those facets. We prioritize this work as we can though. Thanks for your feedback.
