### ISSUE TITLE
Campaign can't be loaded

### ISSUE THREAD

**Issue by seniforu** [RadianSimulations/ghpc-feedback#137]
**Describe the bug**
Whenever I finish playing campaign I press the save button and leave. The next time I want to play campaign I can't load the previous save. I've tried verifying the game integrity but that didn't work. Tried looking for fixes and couldn't find any.

**To Reproduce**

I just save the campaign and close the game.

**Expected Behavior**

I should be able to load my previous saves

**Screenshots**

![Screenshot (2223)](https://user-images.githubusercontent.com/118502622/202619813-c87c134a-ffef-4125-9a9b-3adc8ec3720b.png)

**Comment by blake-bracerstudios** [comment]
Try replicating this issue, and once you have, close and reopen the game, then attach your Player.log and Player-prev.log here. You can find instructions on how to get these in our official Discord linked in the Readme of this repo.

**Comment by blake-bracerstudios** [comment]
Closing as this has gone stale.
