### ISSUE TITLE
Campaign mission with T55A -game crashed.

### ISSUE THREAD

**Issue by kamilllo93** [RadianSimulations/ghpc-feedback#138]
Hello!

When I was playing the Warsaw Pact Campaign with T55A, the game stopped. After the game crashed to Windows.

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 2022.10.30]
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/10096890/Player.log)

**Comment by blake-bracerstudios** [comment]
There is no explicit reason that I could describe for your crash from the player log pinned. Please attach the file located at the bottom of your player log.
