### ISSUE TITLE
Constant crashing in game

### ISSUE THREAD

**Issue by smallchinchilla** [RadianSimulations/ghpc-feedback#139]
I literally cannot remember any time i crashed in game until the past few days ago
Since aprox. 3-4 days or so my game has a habit of crashing, especially when I take a hit or fire a shell (of any tank for any side)
Today I tried uninstalling and re installing the game and the first 10 mins in after a little while in an instant action battle I crashed when firing from my T72

These are my player and player.prev logs from that session
[Player.log](https://github.com/RadianSi
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/10109997/Player-prev.log)
mulations/ghpc-feedback/files/10109996/Player.log)

**Comment by Lotusen** [comment]
The people who know might help you, but I recommend following the outline or addressing the issue at the feedback section from the official GHPC Discord server before doing a bug report.

**Comment by blake-bracerstudios** [comment]
You seem to be having memory allocation issues related to vegetation. We recently released a patch to optimize how much memory was needed for vegetation and it helped, but there are still one-off reports on memory access and allocation.

We're still looking into this and it will be addressed as we have the time. While that may take some time, please let us know your system specs.

**Comment by blake-bracerstudios** [comment]
Rerouting this conversation to #140 and closing is as a duplicate issue.
