### ISSUE TITLE
Post-penetration effect of APFSDS shells isn't correlating with the research papers

### ISSUE THREAD

**Issue by VeeGilante** [RadianSimulations/ghpc-feedback#14]
The amount of spalls produced after penetration of a relatively thin armor is miniscule, usually only 2-3 low energy spalls and the shell itself. Only with the increased penetrated armor thickness the amount of spalls is going up. Research paper taken from the journal ВБТТ №9 (1988 г.) states that the outcome of such penetration should be drastically different and the amount of spalls should also be determined by the residual penetration of a penetrator. Most of the details are fully explained in this article: http://www.tankarchives.ca/2015/03/beyond-armour-effects.html

How to reproduce:
You can reproduce this by shooting Abrams in the hull from the side first - there would be little to no spalls, like on the first image. Then you can shoot it in the turret where the residual penetration of a penetrator will obviously be lower - but the amount of spalls would be drastically higher.

Expected behaviour:
As you can see in this translated table from the paper the amount of spalls increases with the residual penetration of a penetrator for any type of APFSDS, be that heavy alloy or steel.
![изображение](https://user-images.githubusercontent.com/87084993/124794901-2e30d380-df58-11eb-856c-9e0ac6dbba97.png)

Screenshots:
![изображение](https://user-images.githubusercontent.com/87084993/124791326-a1384b00-df54-11eb-88a2-9316a4c81856.png)
_Penetrated the hull - 1 low energy spall_

![изображение](https://user-images.githubusercontent.com/87084993/124791384-adbca380-df54-11eb-91cb-dced7d42b482.png)
_Penetrated the turret - approximately 15-20 spalls with a couple of high energy ones._

Desktop:
OS Windows 10
Version 20210705

Addendum:
I would like to add that, also according to this paper, most of the spalls produced by 3BM22/3BM26 are high energy lethal ones; the cone of lethal fragments created by them is 3 times wider then created by a heavy alloy penetrator with the same residual penetration. It's going to be a beast of a shell ;)

**Comment by blake-bracerstudios** [comment]
Now this is a proper issue report with references. Thank you.

**Comment by JoshBusuito** [comment]
Solved in version 20210808
