### ISSUE TITLE
Palm switch not realistic.

### ISSUE THREAD

**Issue by randyre** [RadianSimulations/ghpc-feedback#142]
**Describe the bug**

Palm Switch when engaged in stabilized mode works correctly, but when disengaged (released) the turret should freeze in both azimuth and elevation.

**Expected Behavior**

1. turret should freeze in both azimuth and elevation. 
2. This should also automatically dump all lead. All lead and lag should be dropped
3. all other ballistic solutions inputs should remain in the computer.
4. lead and lag should not be introduced again until the next time the laser rangefinder is used.
5. This is a standard gunnery technique to engage targets while stationary. Lase target while in turret defalde to get a ballistic solution, dump palm switches, move up into hull down, stop and fire without re-lasing.

 - OS: [ Windows 10]
 - Game Version [20221218.1]

**Additional context**

**Comment by JoshBusuito** [comment]
This is deliberately not implemented to keep consistent stabilizer behavior between vehicles. It may or may not ever change in the future.
