### ISSUE TITLE
M1 Laser needs modes.

### ISSUE THREAD

**Issue by randyre** [RadianSimulations/ghpc-feedback#143]
**Describe the bug**

the laser needs multiple modes.

**Expected Behavior**

The laser needs a first return and last return switch.  First return returns the first bounce of the laser off whatever it hits, last return returns the last return for shooting through bushes, trees, smoke etc.
 - OS: [ Windows 10]
 - Game Version [20221218.1]

**Comment by JoshBusuito** [comment]
"Needs" is a strong term
