### ISSUE TITLE
M1 Needs battlesight button.

### ISSUE THREAD

**Issue by randyre** [RadianSimulations/ghpc-feedback#144]
**Describe the bug**

No battlesight button

**Expected Behavior**

Battlesight button sets range to 1200 for Sabot and 800 for heat. This allows you to shoot without lasing, or to get a quick ballistic solution if you get bad laser returns.

 - OS: [ Windows 10]
 - Game Version [20221218.1]

**Comment by JoshBusuito** [comment]
Ctrl + range down will reset to battlesight distance. This defaults to 1200 meters and there is no intention to change it.
