### ISSUE TITLE
Hard Crash on firing main gun from gunsight view

### ISSUE THREAD

**Issue by aliintag** [RadianSimulations/ghpc-feedback#145]
**Describe the bug**

In the Silver Dart scenario firing the main gun in the gunsight view crashes the game, shuts down my PC, and forces a reboot. Reducing all graphics quality settings to "low" or "disable" and reducing screen resolution seems to extend the number of shots that can be fired, but does not solve the problem.

The crash is instant upon firing the main gun and it feels like it is smoke/effect related.

**To Reproduce**

1. Start Silver Dart scenario 
2. Aim main gun at distant terrain or enemy armour
3. Fire
4. If game does not immediate crash, fire again to induce crash.

**Expected Behavior**

The game permits the main gun to be fired without crashing and rebooting the PC.

**Screenshots**

N/A

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10 Home 22H2 (OS Build 19045.2364)
 - Game Version 20221218.1 *Updated today*

**Additional context**

Intel i7-4770 CPU
32GB RAM
NVIDIA GeForce GTX 1080 Ti with GeForce Game Ready Driver v. 527.56

Player logs attached.
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/10295689/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/10295690/Player-prev.log)

**Comment by blake-bracerstudios** [comment]
The logs attached don't specify a crash from Unity, so more than likely the PC restart is due to a memory or hardware issue exacerbated by the currently higher requirements to run the game. We'll optimize more with time, but this is not an issue we can address at this time.
