### ISSUE TITLE
Cannot complete Tarantula

### ISSUE THREAD

**Issue by 4HCcrashh** [RadianSimulations/ghpc-feedback#147]
After performing the mission "Recon Tarantula" I receive orders to withdraw to "Fallback" position. When I arrive there is no message of the completed mission. I also tried destroying the counter attacking enemy tanks and then fall back. Still no mission complete.

**Comment by blake-bracerstudios** [comment]
This has been fixed at some point by the latest patch. Please update and try again.

**Comment by 4HCcrashh** [comment]
Thank you for the reply but I posted this months ago.  Game looks great.
________________________________
