### ISSUE TITLE
T72M hatch

### ISSUE THREAD

**Issue by PGBen1** [RadianSimulations/ghpc-feedback#152]
You can see into the turret through the left hatch on the turret.

**To Reproduce**

1. Go to anywhere with t72m
2. look at hatch at about 45 degrees
3. see into the turret through crack in hatch

**Expected Behavior**

not seeing into the turret through the hatch

**Screenshots**

![20230201205339_1](https://user-images.githubusercontent.com/124232020/216234869-b31bbcb0-62a4-4874-9861-a985c9b2879b.jpg)

![20230201205338_1](https://user-images.githubusercontent.com/124232020/216234905-128d65b6-9842-4543-9e28-4b4411090522.jpg)

**Desktop (Please complete the following information):**

 - OS: windows 11 home 64bit
 - Game Version 20221218.2

this bug does not appear on the T72M1

**Comment by HankoDobringer** [comment]
this is fixed
