### ISSUE TITLE
AI ATGM Ignore vegetation - Native Narrative 

### ISSUE THREAD

**Issue by tjh88** [RadianSimulations/ghpc-feedback#161]
AI ATGM Ignore vegetation - Native Narrative

AI ATGM behind vegetation is able to target vehicles despite not being able to physically see targets. Missle also ignores direct hits to trees.

**To Reproduce**
1. Run instant action mission Native Narrative in Fulda Gap - Eastern Hills. Order M1 platoon to Halt. Advance forward and kill enemies identified by the commander. Enemies consist of BMPs, T72s, and visible ATGM. 

2. ATGM concealed by trees kills vehicles despite visibility. Missile ignores tree trunks, leaves, etc. 

**Expected Behavior**

I expected to not be targeted by an enemy that cannot physically see targets. Also expected the missile to detonate upon striking vegetation.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/128006548/225487656-2b972666-c121-4346-9f02-e3a8db50b156.PNG)
![Capture01](https://user-images.githubusercontent.com/128006548/225487709-3b62999b-d92c-4d02-8aff-cb532ee3bd4f.PNG)
![Capture02](https://user-images.githubusercontent.com/128006548/225487770-58687905-672d-44db-834b-699b36995f94.PNG)
![Capture03](https://user-images.githubusercontent.com/128006548/225487801-83bddfd2-f94c-48b2-9e93-4673d99713cd.PNG)
![Capture04](https://user-images.githubusercontent.com/128006548/225487830-b9d6a225-0bb0-4c16-9ba8-199ee14b9b4d.PNG)
![Capture05](https://user-images.githubusercontent.com/128006548/225487862-75713da9-979c-46c2-8c44-d33116b4fa89.PNG)

**Desktop**

 - OS: [Windows 10]
 - Game Version [20230228.2]

**Comment by JoshBusuito** [comment]
This was fixed in the early April release.
