### ISSUE TITLE
Random crashes to desktop after April update

### ISSUE THREAD

**Issue by M1sterP1nk** [RadianSimulations/ghpc-feedback#167]
**Describe the bug**

After installing the latest Patch for April 2023 and playing the Aprils Fools Missions the game crashes after some time to desktop.

**To Reproduce**

-Starting Aprils Fools Missions
-Play some time
-Crash to Desktop

**Expected Behavior**

Possibikity to play without crash similar to pre-patch version

**Desktop (Please complete the following information):**

 Betriebsystemname	Microsoft Windows 10 Home
Version	10.0.19045 Build 19045
Zusätzliche Betriebsystembeschreibung 	Nicht verfügbar
Betriebsystemhersteller	Microsoft Corporation
Systemname	FRANKTHETANK-PC
Systemhersteller	Shuttle Inc.
Systemmodell	SH570
Systemtyp	x64-basierter PC
System-SKU	To Be Filled By O.E.M
Prozessor	11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz, 3600 MHz, 8 Kern(e), 16 logische(r) Prozessor(en)

**Additional context**

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11142840/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11142841/Player-prev.log)

**Comment by blake-bracerstudios** [comment]
The logs point to known memory issues in our game, and we address these as we can during development. Please update to the latest build of the game and crashes like these will reduce over time.
