### ISSUE TITLE
Graphics settings menu UX

### ISSUE THREAD

**Issue by Kingrora** [RadianSimulations/ghpc-feedback#17]
**Describe the bug**

in the Graphical settings menu, all of the drop-downs have max settings at the bottom of the drop-down and the lowest settings at the top of the drop-down. But the Texture Resolution drop-down is reversed with the max being at the top and the lowest being at the bottom

**To Reproduce**

no need it is just a UX design feature I guess

**Expected Behavior**

for the  max texture quality setting to be at the bottom to match all of the other drop-downs

**Screenshots**

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20210705

**Additional context**

This is not game breaking and should probably be seen to last but I thought I would mention it here anyway so you had a record of it. it is more of a user experience thing really.

**Comment by blake-bracerstudios** [comment]
While lower priority, consistency is a good idea. Thanks for the heads up.

**Comment by Waffle1434** [comment]
Fixed in dev build
