### ISSUE TITLE
F4 Phantom Accuracy

### ISSUE THREAD

**Issue by Spankythamunky** [RadianSimulations/ghpc-feedback#171]
Im not a F4 Pilot
This fellow John Cheshire is, and an F14 pilot. He will answer on quora, or I can try to contact him as we have spoken before.  He did 2 tours in Nam. He states in this post the F4 never had a hud. 
The Second link is the literal F4 manual from the DCS forums because theyre making the game.  My father was a F4D WSO in the era of the game - his flying days ended in 85 in fact.  The F4 had a sight like an F5, you could set a depression angle and a bullseye reticle would move, but it wasnt like the modern ones aka CCIP (continously computed impact point) or CCRP (same but release point) where the bombs drop when u fly over a selected spot.  Bombing was MUUUUUUUUCH less accurate
As far as load outs just from general knowledge besides tac nukes (ha ha, but Im serious) if for armor they would have carried Mk20 Rockeye cluster munitions.   Im sure dumb bombs would have been racked up too, and napalm.  In ww2 the US found napalm to actually be best for tanks because it was an area weapon.  However the USAF Im almost certain would have used rockeyes.

Quora answer John Cheshires is first - hes the Phantom Pilot and flew the first operational F14 cruise.  Great guy
https://www.quora.com/Did-the-F-4-Phantom-ever-receive-a-HUD-in-the-US-Navy-service

(yes it says in navy svc. he was USN. Its the same for USAF  in 1985 im 99.9% sure)

F4E Manual
https://www.f4phantom.com/docs/F4Manual-1979-T-O-1F-4E-1-Flight-Manual-USAF-Series-F-4E-Aircraft.pdf

Note on the manual page 216-220 has the possible stores loadouts. You can use these for the game.

https://www.f4phantom.com/docs/NATOPS_F4J_manual.pdf

This is the NATOPs. Yeah yeah, I know thats NAVAL F4s, but when it comes to its bombing system they should be identical for dumb bombs.  And Im just doing this right now at the drop of that hat fwiw.

https://milviz.com/Online_products/Manuals/F-4TP.pdf

^ I dont know exactly what this is, Im not saying its a source, but the gunsight I describe in the beginning is shown in cgi or in game shots on this sight. Thats how the F4, F5, and Vietnam era jets bombsights looked.  CCIP is the one that has the plane with a line and a little circle with dot attached that continously 'tracks' along the ground.

The first US plane to get a HUD was the A7 Corsair.

**Comment by JoshBusuito** [comment]
At this time we are not interested in corrections to CAS bomb accuracy, as the April Fools missions were set up with work-in-progress jet systems and deliberately made difficult.
