### ISSUE TITLE
Odyssey Mission - Selecting Night doesnt Work

### ISSUE THREAD

**Issue by Spankythamunky** [RadianSimulations/ghpc-feedback#173]
I noticed if you select night its like the mission is 'unselected' however the title of the mission is still there.

regardless, you cannot play this at night by selecting night as of right now

**Comment by blake-bracerstudios** [comment]
Fixed for next patch.

**Comment by Spankythamunky** [comment]
Impressive as always.  Though I really just want my beloved (T64). Ive
spent more time than I want to admit just ogling it in Grafenwohr
