### ISSUE TITLE
Stutters "buildup" in consecutive campaign missions lead to unplayability

### ISSUE THREAD

**Issue by NextTomShark** [RadianSimulations/ghpc-feedback#175]
A problem I know since I bought the game in Sept2022, but getting worse and worse:
increasing stutters/freezes after consecutive campaign missions. First mission runs smooth, no probs at all. Second mission is already unplayable (FPS 1-10), with some sudden episodes of fluid game running for a couple of seconds. After ending the mission, it takes an eternity to get back to the menu and even longer to start the next mission. The next one is more a freeze that a stutter.
Problems occur from the start, changing optics, openiung map, switching to thermal makes it even worse. Enemy encounters also seem to have negative effects. 
When i restart the game and go on with the missions, the first one will works absolutely smooth. 
The issue is the same with random instant action misison, but not to the extent as it occurs with campaigns.

my machine is a bit dated indeed and i play on reduced settings, but still its basically possible to run the game absolutely smooth and playable, just only one mission.

Acer Aspire U5-620
Microsoft Windows 10 Home (10.0, Build 19045)
Intel(R) Core(TM) i7-4712MQ CPU @ 2.30GHz 4/8
RAM: 8 GB
SanDisk Cruzer Glide USB Device (29,3 GB/Removable Media)
Seagate Expansion SCSI Disk Device (1,8 TB/External hard disk media)
WDC WD10JPVX-22JC3T0 (931,5 GB/Fixed hard disk media)
NVIDIA GeForce GTX 850M (2 GB)
Intel(R) HD Graphics 4600 (1 GB)

**Comment by blake-bracerstudios** [comment]
This is less of a beg and more a highlight of an issue that's known with our current optimizations. More than likely with your set up, there is a bottleneck when trying to clean out/use memory as you load new missions/try new features. While you meet minimum specs, the game is requiring more than this hardware configuration can keep up with. Our small team addresses optimization issues as we can during development.
