### ISSUE TITLE
Binocular texture stays on when using freecam

### ISSUE THREAD

**Issue by Nico-but-with-a-sword** [RadianSimulations/ghpc-feedback#176]
**Describe the bug**

Binocular texture stays on if you use the freecam until you use binos again

**To Reproduce**

1. Go to binocular view when using the unbuttoned view
2. press F3 the bino mask will stay on
3. Press F3 again you are now in wide view with the mask applied and the mouse DPI reduction too
4. Zoom again then back out to fix the issue

**Expected Behavior**

Binocular masking png disappearing when going in freecam, returning either to wide view without the mask or returning to zoomed in view with it. 

**Screenshots**
[webm of the issue](https://cdn.discordapp.com/attachments/572120277337505823/1097487099772555394/bug_report.webm)

**Comment by blake-bracerstudios** [comment]
Fixed quite some time ago.
