### ISSUE TITLE
Crash to desktop every time game starts in "Instant"

### ISSUE THREAD

**Issue by gergIndo** [RadianSimulations/ghpc-feedback#177]
**Describe the bug**

Started 4 separate missions, all "instant"......:Indomitable Invasion", "Intrepid Invasion", each mission crashed as soon as the loader says "Sabot Up"...

**Desktop (Please complete the following information):**

 - OS: Edition	Windows 10 Home
Version	21H2OS build	19044.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0
 - Game Version 20230401.2
Processor	AMD Ryzen 5 3600X 6-Core Processor                3.80 GHz
Installed RAM	16.0 GB

**Additional context**

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11315245/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11315246/Player.log)

**Comment by gergIndo** [comment]
game is unplayable for me right now, crash everytime within 1st minute of starting.

**Comment by Hells-Grannies** [comment]
Have had the same issue before and after the most recent update. Game crashes ~15 seconds after the mission loads, happens with most Instant Action missions.

Windows 10
Version 21H2 Build 19044.2965
i5-6500 3.2 GHz, 16 GB RAM, GeForce GTX 1080
Game Version 20230519


[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11521266/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11521268/Player-prev.log)

**Comment by blake-bracerstudios** [comment]
There have been several optimizations to the game at this point. Please try again and post a new player.log when able.
