### ISSUE TITLE
M60A3 TTS Thermal Sight Permanently On After Weapon Switch When On

### ISSUE THREAD

**Issue by IamBriOnGitHub** [RadianSimulations/ghpc-feedback#178]
**Describe the bug**

The thermal sight for M60A3 TTS seems to be "stuck on" if you enter thermal sight mode, then switch weapons from the cannon to either of the machineguns. When switching back to the cannon, the thermal sight cannot be disabled.

**To Reproduce**

1. Go to any mission with an M60A3 (I tried Steel Wedge / Blue side to test just now)
2. In an M60A3 TTS, enter gunner view
3. Engage thermal sight
4. Switch weapon to .50 cal/7.62
5. Return to cannon
6. At this point, thermal sight seems to be stuck on.

**Expected Behavior**

Thermal sight disengageable as needed

**Screenshots**

N/A

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10 Home
 - Game Version 20230401.02

**Additional context**

N/A

**Comment by blake-bracerstudios** [comment]
Fixed.
