### ISSUE TITLE
Campaign loss reporting exaggerations

### ISSUE THREAD

**Issue by rossmum** [RadianSimulations/ghpc-feedback#180]
**Describe the bug**

Losses in campaign (friendly and enemy) are overreported. I initially thought the losses had been switched to cumulative as in a single mission I was told I had killed more men and materiel than in the previous 3 missions combined, but the next two missions had similarly large numbers. Known friendly vehicle losses are overreporting by a factor of 2 so I expect the same is happening with crew and with enemy losses.

**To Reproduce**

1. Do a campaign mission.
2. Kill some things.
3. Count up killed vehicles in AAR, write it down.
4. Compare to what post-mission report tells you.

**Expected Behavior**

Number not go up.

**Screenshots**

N/A

**Sources**

The reports of my death have been greatly etc., etc.

**Desktop (Please complete the following information):**

 - OS: W10 Home 22H2
 - Game Version 20230519 + both hotfixes AFAIK

**Additional context**

This campaign was started a night or two before the patch. I am unsure if this is related or not. I guess I'll find out if I finish this one quickly and the next one has the same issue.

**Comment by rossmum** [comment]
update: overreporting by double seems to match up with my AAR observations

**Comment by JoshBusuito** [comment]
Fixed by RadianSimulations/GHPC-vertical#1242
