### ISSUE TITLE
Crashing during the first part of Pragmatic Payment

### ISSUE THREAD

**Issue by Keo9143** [RadianSimulations/ghpc-feedback#182]
**Describe the bug**

Every time I attempt to secure the first objective of the first mission in Pragmatic Payment, my game crashes. No other mission has given me trouble.

**To Reproduce**

1. Launch the first Pragmatic Payment mission
2. Fight my way to Objective Anton
3. Attempt to drive onto the objective to secure it
4. This is when the game crashes.

**Expected Behavior**

Player should be able to capture the objectives without the game crashing.

**Screenshots**

N/A

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20230519.2

**Additional context**

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11538547/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11538549/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11538554/Player.log)

**Comment by blake-bracerstudios** [comment]
The asset causing a memory leak has been removed as of 20231031. Try again and if the issue persists, post a new log file.
