### ISSUE TITLE
Hard crashes on the 2nd mini campaign mission

### ISSUE THREAD

**Issue by Imightbehum4n** [RadianSimulations/ghpc-feedback#183]
Give the Unity crash tracker however about 2 seconds after that program begins my whole PC crashed. Couldn’t Alt + Tab nor could I ctrl + alt + delt my way out of it. 

I haven’t attempted to reproduce however I will describe everything that I did to somehow cause the issue

1. Go to the 2nd dynamic campaign mission on fulda outskirts 
2. Stay on your original vehicle and drive forward with a echelon left (I don’t think it’ll affect it but I did this in the mission)
3. Go into your sight about 2 or so minutes after spawning in and then click M.
4. Error might occur unless it was just a one off event

Your screen as soon as the M key is hit should freeze, the Unity crash auto tracker will try to analyse however it will close after 2 seconds then your screen will just be black.

 - OS: Windows 10
 - Game Version: Most recent version for public usage as of the 23/5/2023
 - A few basic specs: RTX 3070, 16gb of ram and the game is stored on a external hard drive

**Comment by blake-bracerstudios** [comment]
Closing as there have been several updates since posting.
