### ISSUE TITLE
Strong game lag and freezes

### ISSUE THREAD

**Issue by Mrljavi** [RadianSimulations/ghpc-feedback#186]
Strong game lag, so it becomes unplayable. Sometimes the game freezes and the only way to turn it off is with ALT+F4. The sound in the game sometimes goes into a "loop", so, for example, the sound of a grenade being fired or an explosion sounds like a burst. Most often everything freezes then.
It is not a problem in all missions and in the whole campaign, but in most missions and during the campaign the same problem happens.

**Desktop (Please complete the following information):**
 - OS: [Windows 10 Pro / 64]
 - Game Version [e.g. 20230519]

[Player-prev_01.log](https://github.com/RadianSimulations/ghpc-feedback/files/11642283/Player-prev_01.log)
[Player-prev_02.log](https://github.com/RadianSimulations/ghpc-feedback/files/11642284/Player-prev_02.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11642286/Player.log)

**Comment by blake-bracerstudios** [comment]
Related to #211
