### ISSUE TITLE
Game Crashing while playing some missions

### ISSUE THREAD

**Issue by Mrljavi** [RadianSimulations/ghpc-feedback#190]
I am reporting a bug for the same mission that I tried twice. Both the first and second time the game stopped working and kicked me to the desktop.

Expected Behavior
The Unity crash (if I understand the message correctly)

Screenshots
N.A.

Desktop (Please complete the following information):

OS: Windows 11
Game Version 20230622

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11872143/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11872144/Player-prev.log)

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11872148/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11872149/Player-prev.log)

**Comment by blake-bracerstudios** [comment]
Related to #140
Optimizations are in progress.
