### ISSUE TITLE
Game crashes when starting any mission, instant or campaign.

### ISSUE THREAD

**Issue by runway37** [RadianSimulations/ghpc-feedback#191]
**Describe the bug**

Game crashes when starting any mission, instant or campaign. About 3 seconds after I hear "Sabot loaded" the game crashes to desktop. Tried the M1IP and M60 training missions and one campaign mission, Fulda Gap.

**Are you playing with mods?**

No

**To Reproduce**

1. Go to Instant
2. Click on M1 or M60 training missions
3. Game crashes to desktop shortly after loading

**Expected Behavior**

Not crashing

**Screenshots**

**Sources**

NA

**Desktop (Please complete the following information):**

 - OS: Windows 11
 - Game Version 20230622.1

**Additional context**

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11987166/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11987168/Player-prev.log)

Update July 8, 2023:
Uninstalled the game, reinstalled. Tried the M1 training mission again and the game crashed as quickly as before, this time the computer rebooted as well.

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11991349/Player.log)

**Comment by blake-bracerstudios** [comment]
Reviewed logs and it's related to #140. Closing as duplicate
