### ISSUE TITLE
Game crashes (Instant - "Crossroads Screen")

### ISSUE THREAD

**Issue by Mrljavi** [RadianSimulations/ghpc-feedback#192]
Describe the bug

Game crashes right after i finished almost the whole mission ("Crossroada Screen"). All that was left for me was to go back to WP15.  

Are you playing with mods?
No
To Reproduce

After getting a notification for one task left (return to point 15), I opened the map and after that the game crashed.

Desktop (Please complete the following information):
OS: Windows 11
Game Version 20230622

Additional context
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/12015392/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/12015394/Player-prev.log)

**Comment by blake-bracerstudios** [comment]
Reviewed the logs and it's related to #140. Closing this for now as we're looking to optimize these assets soon.
