### ISSUE TITLE
Cannot proceed beyond menu screen

### ISSUE THREAD

**Issue by swampfox1** [RadianSimulations/ghpc-feedback#194]
The game won't go beyond the 'intro' screen.  When I open the game in Steam I get the options menu in a black box over a moving screen of a wooded area with different vehicles.  When I click on any of the options the black box and all options disappear and all I'm left with is the moving wooded background.  I can recall the menu box by pressing the Esc key, but clicking on any option makes the black menu screen disappear again.  I cannot progress along any of the menu options. The only way I can close the game is with the Task Manager.  I have verified my files with Steam, and I have deleted and reinstalled the game, but none of that helped.  My computer is beyond 'recommended' stats, and I have made no downloads to my computer either in or beyond Steam prior to finding this problem.  I haven't played GHPC a lot, but this is the first problem I've had, and I've found this problem with no other Steam game.

**Comment by blake-bracerstudios** [comment]
Have you made any changes to your keyboard or to your key mapping in the game's options before this started happening? It sounds like your click has been mistakenly mapped to cancel. As a potential fix, please:

1. Open Windows Registry Editor (search regedit in your Start menu to find it quickly).  BE CAREFUL with this tool, as it can be very dangerous to your PC stability if used improperly.

2. Browse to Computer\HKEY_CURRENT_USER\SOFTWARE\Radian Simulations LLC\GHPC

3. In the right-hand side panel, find all entries with "Rewired" in their name and delete them.

4. Run GHPC.  The controls should all be returned to default.

**Comment by swampfox1** [comment]
Blake...

I did not knowingly make any changes to my keyboard or key mapping, but I followed your instructions and deleted all the entries with "Rewired", and it worked!  I restarted the game and the menu worked.  I entered the tank range and everything seemed to operate just as it should...  I have no idea how this happened, but thank you for your prompt reply and your help...  Cheers...

Joe
________________________________

**Comment by blake-bracerstudios** [comment]
Glad to hear it!
