### ISSUE TITLE
M1 & M1IP hit by HEAT, jet ignores side hull/crew compartment

### ISSUE THREAD

**Issue by Efferrari** [RadianSimulations/ghpc-feedback#196]
**Issue:**
-HEAT jets are passing entirely through the hull of both the M1 & M1IP even when they should be creating internal spall. 
-Spall created from the jet on the first skirt is also properly blocked by the hull, so it seems to be the jet itself having issues.
-When hit, the jet passes through to the other side of the hull and then creates spall as normal when exiting through opposite skirt. 

**Not playing with mods.**

**Steps to reproduce the behavior:**
1. Equip HEAT or ATGM (see extra notes below for rounds that are functioning properly)
3. Shoot the centermost skirts of an M1/M1IP
4. End match 
5. Using the shot tracker, observe the jet passing entirely through the tank and creating no damage inside the crew compartment

**Extra Notes:**
-HEAT rounds that function properly: BK-354M from the PT-76, and PG-15V from the BMP-1 (though still create little spall)

**What should be happening:**
Clean side hits like the ones in attached images should be causing massive internal damage

**Computer Information**
 - OS: Windows 10
 - Tested on version 2023081

**EXAMPLES OF HEAT JETS NOT CREATING SPALL**

![M1 vs HEAT no spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/e1f376fc-a166-4cf6-87f9-33e8c135220f)

![M1IP vs HEAT no spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/3cb15fc8-8256-4ee8-b4f5-c7647afd5515)

![M1 vs TOW no spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/477698dd-a852-4e33-9eaa-d7f02cac1489)

![M1IP vs TOW no spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/ed3afd59-8752-47cf-93e4-ab7809ac4f8d)

![M1IP vs Konkurs no spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/187bcefd-856d-4c12-bd1f-5a51c95f4d55)

![M1IP vs M60 M456 HEAT no spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/62ba6de8-2aef-4329-ba51-522facb2b8b0)

![M1IP vs T55A HEAT no spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/51253de5-7fb0-45ec-b486-82158bf08c9a)

**BELOW ARE SHOTS FROM THE PT-76 AND BMP-1 THAT ARE CREATING SPALL**

**BELOW ARE SHOTS FROM THE PT-76 AND BMP-1 THAT ARE CREATING SPALL**

**BELOW ARE SHOTS FROM THE PT-76 AND BMP-1 THAT ARE CREATING SPALL**

![M1IP vs PT76 HEAT yes spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/9f052ee2-e14b-4230-9986-2e8b3267d3cc)

![M1IP vs PG15V yes spall](https://github.com/RadianSimulations/ghpc-feedback/assets/118708902/c6a4cfaa-0898-4206-ada0-6607cb14c3a1)

**Comment by JoshBusuito** [comment]
The formulas for spall creation are based on real-world tests and influenced by many factors including the thickness of the armor and the remaining penetrative power of the HEAT jet. If you would like us to change these formulas, you will need to provide evidence that it should not be performing this way. The current results line up with documentation we've seen.

**Comment by Efferrari** [comment]
> The formulas for spall creation are based on real-world tests and influenced by many factors including the thickness of the armor and the remaining penetrative power of the HEAT jet. If you would like us to change these formulas, you will need to provide evidence that it should not be performing this way. The current results line up with documentation we've seen.



I guess this will change when the interiors are modeled instead of being just void?

I feel like the jet should be impacting with the turret basket and hitting at least SOME metal that isn't protected by spall liners if it was going through and through. The current model claims there is zero risk to the crew from damage caused by the jet.

:/

https://www.youtube.com/watch?app=desktop&v=5Em6dyapAt4
