### ISSUE TITLE
optics stop working after some switches

### ISSUE THREAD

**Issue by Zebrone1** [RadianSimulations/ghpc-feedback#198]
**Describe the bug**

I used an M60 TTS and RISE but i haven't tried with other tanks yet, changing the visual to aim and using zoom and other apparatus, like thermals disable the use of optics.

**Are you playing with mods?**

No

**To Reproduce**

1. Press Shift to aim
2. use the scroll wheel to zoom in and out
3. at the same time switch guns and thermals
4. after some tries the game don't let you use the optics anymore pressing shift

**Expected Behavior**

Disabled optics

**Screenshots**

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: Windows 11
 - Game Version [e.g. 20230810]

**Additional context**

**Comment by blake-bracerstudios** [comment]
Cannot reproduce. Post your player.log next time this happens.
