### ISSUE TITLE
The game crashes every time I`m trying to play

### ISSUE THREAD

**Issue by MAXO123321** [RadianSimulations/ghpc-feedback#199]
**Describe the bug**

Every time Im trying to play this game its crashing for absolutely no reason. Also shortly after it happens my PC changes the monitor extension.

**Are you playing with mods?**

No.

**To Reproduce**

1. Launch game from Steam;
2. Go to Instant Action;
3. Choose any mission;
4. Wait for 10 seconds;
5. Game crashes.

**Expected Behavior**

I expected to play and try the new update.

**Screenshots**

I wasnt able to make a screenshot, because i couldn`t take it while the game was crashing.

**Desktop:**

 - OS: Windows 10
 - Game Version 20230810

**Additional context**

Here are the logs

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/12338570/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/12338571/Player-prev.log)

**Comment by blake-bracerstudios** [comment]
After chatting in the discord, it's odd that this happens with a noted 32GB of RAM, but if you could post your major system specs here, that would be useful.

Otherwise, as stated in the discord, this is most likely a duplicate or related issue to #140 which we are aware of.

**Comment by Spudicous** [comment]
I've been having a similar issue, but I normally last 3-5 minutes in the missions before I crash either to desktop or am forced to restart my computer.
AMD Ryzen 7 7800X3D 8-Core Processor              4.20 GHz
32.0 GB (31.2 GB usable)
4070ti
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/12402664/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/12402665/Player.log)

**Comment by Space-Janitor-Named-Oleg** [comment]
Have the same issue but the game crashes before it loads, it goes black and then a couple seconds later terminates and locks up any other open applications 
system specs:

Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	8.00 GB (7.73 GB usable)
Windows 11
System type	64-bit operating system, x64-based processor

**Comment by blake-bracerstudios** [comment]
Closing this as part of issues related to #140. Crashes may still persist and we're working on addressing those as they come up/as devs become available to do so.
