### ISSUE TITLE
Crash To Desktop / Hang (VSP)

### ISSUE THREAD

**Issue by Waffle1434** [RadianSimulations/ghpc-feedback#2]
**Describe The Bug**
Vegetation Studio Pro sometimes creates memory access violations, resulting either in a crash to desktop or a very long freeze. Look for memory access violations in the log file at `%USERPROFILE%\AppData\LocalLow\Radian Simulations LLC\GHPC\output_log.txt`

**Potential Solutions**
1. Manually increase system pagefile size

**Comment by blake-bracerstudios** [comment]
Oddity and a big ask to make people change their system pagefile size for a game. Will need to look into this more.

**Comment by blake-bracerstudios** [comment]
We'll be shifting and optimizing more as time goes on, so this will either be looked into as the system grows or we will yeet VSP for something else. Manual page file resizing on machines is a NO.
