### ISSUE TITLE
Second Penetration of HEAT Jet Produces Little To No Spall

### ISSUE THREAD

**Issue by RussianBot9** [RadianSimulations/ghpc-feedback#20]
**Description of the bug**

The second penetration of any HEAT jet produces little to no spall

**To Reproduce**

1. use any vehicle with two layers of armor close to each other. some example would be the BRDM2 LFP, M113 flotation plate, and M1IP side skirts  
2. using any HEAT warhead hit the part of the vehicle with the second layer of armor
3. observe large post pen effect for first layer of armor then very little for the second. However, the HEAT jet still penetrates and if there is a third penetration it can have a large amount of spall.

**Expected Behavior**

A large amount of spall for both penetrations, especially when using TOW or fagot ATGMs

**Screenshots**
shot hits side skirt
![image](https://user-images.githubusercontent.com/88638437/128652791-96c94e34-e9fb-4400-8492-26a07491d83f.png)

shot hits main body 
![image](https://user-images.githubusercontent.com/88638437/128652850-64a6a183-8ba5-45f6-bcfe-24adf5010ce8.png)

shot hits floatation panel 
![image](https://user-images.githubusercontent.com/88638437/128652867-19255880-a68b-4dcf-99ec-9ca6b48d5b1b.png)

shot hits main body
![image](https://user-images.githubusercontent.com/88638437/128652896-7e5055b4-11a8-45d3-8bcf-c481a3b8e972.png)

shot hits fording shield
![image](https://user-images.githubusercontent.com/88638437/128652920-91263b61-3698-4000-b613-f43840336eb2.png)

shot hits main body
![image](https://user-images.githubusercontent.com/88638437/128652943-cadc725e-cab6-40bd-9e34-d351e5a4914a.png)

**Desktop Info**

 - OS: Windows: 10
 - Game Version: 20210808.1

**Additional context**
 I showed screen shots of M60A3 HEAT but similar results were seen when using TOW, T55, and T72

**Comment by JoshBusuito** [comment]
Fixed in previous release
