### ISSUE TITLE
Attack axis intel wrong on [insert_map_name_here]

### ISSUE THREAD

**Issue by Bigsky22** [RadianSimulations/ghpc-feedback#201]
**Describe the [bug**]

On this map(see screenshots), campaign, at least twice the enemy attack axis is incorrectly stated by recon.

**Are you playing with mods?**

no

**To Reproduce**

Find a mission on this map w/ defend position
Hope attack axis is (actually) 1
See message for axis 2
get hit from axis 1
profit?

**Expected Behavior**

Incorrect axis displayed/enemies attacking from

**Screenshots**

![2023-08-25T062140](https://github.com/RadianSimulations/ghpc-feedback/assets/111603763/90382df4-5749-425d-b0de-3c03598b9edc)
![2023-08-25T062250](https://github.com/RadianSimulations/ghpc-feedback/assets/111603763/abde5fbc-36b1-4f03-b756-d253f381b620)

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: Win 10
 - Game Version Steam latest

**Additional context**

**Comment by blake-bracerstudios** [comment]
Recon confidence is displayed in the mission briefing, and they can be wrong. Each point is noted as possible points of attack.
Campaign will be getting more changes as development continues, so not a bug per se.
