### ISSUE TITLE
Crash on Raid mission in campaign 

### ISSUE THREAD

**Issue by Toxi2202v2** [RadianSimulations/ghpc-feedback#202]
Game randomly crashed and closed it self on a Raid mission while i was driving in a T-72M i dont know the cause of the crash so player logs are included in this post

To Reproduce

1. Go to campaign mode
2. Click on a Raid mission
3. Play the mission
4. Error should randomly happen

Expected Behavior:
Game should freeze for a second and then crash and close itself

Screenshots:
None made

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20230905

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/12620724/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/12620725/Player.log)

**Comment by blake-bracerstudios** [comment]
While there was a crash as listed in the logs, Unity did not output a stack track to help us verify anything. Closing for now since the game has been updated and this may no longer be the case.
