### ISSUE TITLE
T 55 AMB2

### ISSUE THREAD

**Issue by ingrahammark7** [RadianSimulations/ghpc-feedback#203]
**Describe the bug**

Add T55 upgrades

**Are you playing with mods?**

N

**To Reproduce**

Incel

**Expected Behavior**

East Germany had the T-55AMB2 upgrade. Even if it was in negligible numbers they did have laser range finder missile capable T-55. Soviets had laser range finding before America did. 

Also the BRDM had sagger variants whereas America never had worthwhile light anti tank vehicles. The ITOW/Cherrypicker was never widely deployed. Every soviet vehicle in the game should be capable of using advanced weapons (laser, SACLOS etc) to kill tanks. 

The Bradley has no stabilizer as that was added in the 2000s as the ODS SA. The early Abrams had no armor inserts and virtually no armor.

Soviet armor was fiberglass so it was far stronger than its RHA rating. RHA assumes a hard penetrator, fiberglass is stronger than DU so it was 3-10x stronger than a simple RHA calculation. 

The viewport in the Bradley are also incorrect, you are using the SA and not the old one.

**Screenshots**

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**Additional context**

**Comment by JoshBusuito** [comment]
Closed due to lack of sources
