### ISSUE TITLE
THIS game image is great but just Vehicle comes more the LAG problems become more terrible,and the ammo too little with insufficient firepower,make too hard to play in a mission.

### ISSUE THREAD

**Issue by M1A4** [RadianSimulations/ghpc-feedback#208]
**Describe the bug**

**Are you playing with mods?**

Yes or no. If yes, please note which mods here. Any third-party content may be incompatible with GHPC's ongoing updates. While issues related to third-party content are not a priority for development, known conflicts can be reported for other users.

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**Additional context**

**Comment by JoshBusuito** [comment]
Closed for incoherence and failure to follow reporting format
