### ISSUE TITLE
The game crashes and the computer restarts.

### ISSUE THREAD

**Issue by Mrljavi** [RadianSimulations/ghpc-feedback#211]
**Describe the bug**

After the beta update and the new non-beta update, the game restarts the computer. This happens only in GHPC. No other game gives me the problem.

**Are you playing with mods?**

No

**Desktop (Please complete the following information):**

 - OS: [Windows 10]
 - Game Version [20231031]

**Additional context**

After upgrading the game works significantly better, everything runs smoothly, the sound is better and the behavior of the game itself, but:
The game crashed after the mission was completed. I tried to go back to the main game menu (Esc. key) and the computer restarted without my interaction. The same thing happened with the beta version a few days ago. Before these two upgrades, I didn't have such a problem with GHPC. All other games work on the computer without any problems.
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/13213010/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/13213011/Player-prev.log)

I tried again... I started the game after 3 hours from the first post and after a few minutes the game restarted my PC. I am also attaching that one *.log file
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/13215408/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/13215409/Player-prev.log)

I also attached a screenshot of the map (*.zip) and marked two places on the map where the PC always restarted when I came to those places. This happened in the beta test version a few days ago. I haven't tried this mission with today's regular update.
[GHPC_CrashPlace.zip](https://github.com/RadianSimulations/ghpc-feedback/files/13213204/GHPC_CrashPlace.zip)

**Comment by blake-bracerstudios** [comment]
Since the crashes are rebooting your machine, there is no Unity stacktrace available to troubleshoot. You can try to find your crash dump file if this persists (the path is unique to your machine, you can find it in your Player.log file), but otherwise crash to reboots are usually an indicator of hardware being pushed well past its limits or of potential failure.

If it happens again, post a crash log and your system specs and we will review them.
