### ISSUE TITLE
In quick start mission J no longer shows breifing.

### ISSUE THREAD

**Issue by PatrickH1962** [RadianSimulations/ghpc-feedback#216]
**In quick start mission J no longer shows breifing.**  Cross Roads Screen & Native Narrative tried.

**Are you playing with mods?** No.

Yes or no. If yes, please note which mods here. Any third-party content may be incompatible with GHPC's ongoing updates. While issues related to third-party content are not a priority for development, known conflicts can be reported for other users.

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**Additional context**

**Comment by blake-bracerstudios** [comment]
As of 20231031, the briefing and objectives info have been moved into the Map view. Press M and expand the mission title bar in the top left of the map, and you'll see the briefing. Look to the left, and you'll see the objectives.

**Comment by PatrickH1962** [comment]
Cheers Blake. Sent from Mail for Windows From: Blake FarrugiaSent: 07 November 2023 16:56To: RadianSimulations/ghpc-feedbackCc: PatrickH1962; AuthorSubject: Re: [RadianSimulations/ghpc-feedback] In quick start mission J no longer shows breifing. (Issue #216) As of 20231031, the briefing and objectives info have been moved into the Map view. Press M and expand the mission title bar in the top left of the map, and you'll see the briefing. Look to the left, and you'll see the objectives.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
