### ISSUE TITLE
Silver dart mission inconvenience

### ISSUE THREAD

**Issue by R3ivik** [RadianSimulations/ghpc-feedback#219]
Hi, so when i was playing the silver dart mission, i noticed that my abrams's turret was stuttering but still my fps was pretty okay(about 90).Then, i moved to a position and started shooting t72s that were charging towards me.What ended up happening was that uhh, take a look: 

![Gunner Heat Pc Screenshot 2023 11 14 - 18 59 13 43](https://github.com/RadianSimulations/ghpc-feedback/assets/150837792/d843a9d0-28c3-4aa6-849c-13ef0277e2f1)

Im not using any mods and for example last week when i played the game was running smoothly.

**Comment by blake-bracerstudios** [comment]
Known and part of #220. Closing this as a duplicate.
