### ISSUE TITLE
Commander vision blocks on the preview Leopard 1 on Grafenwoehr showcase whole tank texture

### ISSUE THREAD

**Issue by Nico-but-with-a-sword** [RadianSimulations/ghpc-feedback#231]
**Describe the bug**
Vision blocks on the preview Leopard 1 on Grafenwoehr showcase whole tank texture

**Are you playing with mods?**

No and I won't.

**To Reproduce**

1. Go to Grafenwoehr
2. Look at the Leo 1 vision blocks on the commander's cupola

**Expected Behavior**

Vision block texture

**Screenshots**

![image](https://github.com/RadianSimulations/ghpc-feedback/assets/117083375/016cff3a-3a2c-4e15-b69b-a1b86935b1e7)
![image](https://github.com/RadianSimulations/ghpc-feedback/assets/117083375/d5718f63-38f4-4ff7-9e71-d77215b3f4cd)

**Sources**

Found by Lev Matienko on the GHPC discord

**Desktop :**

 - OS: irrelevant
 - Game Version: 20231208.1

**Comment by HankoDobringer** [comment]
[WNF.](https://www.acronymfinder.com/Will-Not-Fix-(WNF).html)

**Comment by Nico-but-with-a-sword** [comment]
Based.
