### ISSUE TITLE
Cant save campaign

### ISSUE THREAD

**Issue by Wakoheart** [RadianSimulations/ghpc-feedback#233]
**Describe the bug**
Everytime I go to campaign and try to save a campaign it does not save and when I go back to the main menu click campaign to countinue I cant find the saved campaign as it was never saved.
 
(no mods used)
(not sure how I got the issue)

**Comment by blake-bracerstudios** [comment]
Please attach your Player.log from a run where you were not able to save the game so we can review.

**Comment by Wakoheart** [comment]
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/14057001/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/14057002/Player-prev.log)

**Comment by brikabrak** [comment]
Found that the expected path to save the campaign data is not yet created, so the process errors out. Will put this on our board to fix. Thanks.
