### ISSUE TITLE
 [Linux] AAR skips some shots when pressing A/D

### ISSUE THREAD

**Issue by physixcat** [RadianSimulations/ghpc-feedback#235]
**Bug Description**

On Linux, when viewing After Action Report and cycling through shots with keyboard buttons A and D (previous/next), the game skips shots. For example, it will be on shot#1, you press D, and it will very briefly show shot#2 and immediately move to shot#3.

I can sometimes get it to show the "skipped" shot by moving up a shot and then tapping the "previous shot" button twice, but it is very finnicky. 

**Are you playing with mods?**

No.

**To Reproduce**

1. Start any mission with any vehicle, use any gun
2. Shoot about 6 times
3. End mission, go to AAR, unselect "only show hits" / "exclude small caliber" option (if it was used)
4. Press D to move to next shot
5. Every other shot will be skipped over (it will go 1 to 3, 3 to 5, 5 to 1)
6. It is possible to prevent this by spamming A right after D, and then it will become 2-4, 4-6, 6-2 

**Expected Behavior**

Pressing A/D keeps the prev/next shot displayed, instead of skipping over it (1,2,3,4,5,6).

**Screenshots**

None.

**Player Log**

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/14068514/Player.log)

**Sources**

None.

**Desktop (Please complete the following information):**

 - OS: Debian GNU/Linux trixie/sid x86_64
 - Game Version: 20240124 (but it has happened since previous versions as well)
 - Proton Version: GE-Proton8-4 (but it has happened with others as well)

**Additional context**

It should be noted this particular problem has been reported in the game's ProtonDB entry before
https://www.protondb.com/app/1705180
![2024-01-26-130548_1920x1080_scrot](https://github.com/RadianSimulations/ghpc-feedback/assets/32757992/723881ce-40cf-49c8-ba16-8b8a01e6a787)
If this can't be reproduced on Windows, then it's probably an issue with Wine/Proton doubling the input for some reason, but I have not seen this happen in any other game, Unity or otherwise. I wonder if there's something particular about the way the shot cycling is done in GHPC that can result in a double input?

**Comment by brikabrak** [comment]
We do not officially support Linux at this time, so we cannot reproduce this issue on our current dev systems.
