### ISSUE TITLE
Game only playable for 10 or so minutes before it pegs memory on GPU and causes crash. Had zero issues before last update.

### ISSUE THREAD

**Issue by brose88** [RadianSimulations/ghpc-feedback#237]
**Describe the bug**

Game only playable for 10 or so minutes before it pegs memory on GPU and causes crash. Had zero issues before last update.

**Are you playing with mods?**

No

**To Reproduce**

1. Play game for more than 10 minutes in mission.

**Expected Behavior**

Not Crash

**Screenshots**

**Player Log**

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/14072988/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/14072989/Player-prev.log)

If the player log includes a reference to a crash.dmp file, you should attach that as well.

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS:  Windows 10
 - Game Version 20240124

**Additional context**

**Comment by blake-bracerstudios** [comment]
Consolidating under #238
