### ISSUE TITLE
20240124: Very low FPS (1-15FPS)

### ISSUE THREAD

**Issue by AlexD2016the2nd** [RadianSimulations/ghpc-feedback#238]
After a couple minutes of playing, the game starts getting really slow (from 50-70FPS to 20FPS) and then eventually crawls to a halt at 1-5FPS. To be noted that Task Manager shows normal CPU/GPU/RAM usage, not 100%.

I don't use any mods or steam commands. And I play both on Windows11 and Linux Mint, the issue happens on both.

**To Reproduce**

1. Launch GHPC
2. Load any mission and play
3. The bug will appear on the first or second mission after a couple of minutes

**Expected Behavior**

I expected 100% usage on all my resources when the FPS got very low.

**Player Log**

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/14102051/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/14102052/Player-prev.log)

If the player log includes a reference to a crash.dmp file, you should attach that as well.

**Desktop**

 - OS: Windows 11 (but happens on Linux Mint too)
 - Game Version 20240124

**Comment by blake-bracerstudios** [comment]
Currently vetting a hotfix for this.

**Comment by blake-bracerstudios** [comment]
The hotfix was pushed about a week ago, but we immediately saw issues were still cropping up on some machines. We pushed an additional change to turn off the suspected system and found no issues were recurring.

I've rewritten the culprit system and it is now in testing.
