### ISSUE TITLE
Test build crashes PC

### ISSUE THREAD

**Issue by auggywoggy** [RadianSimulations/ghpc-feedback#24]
**Describe the bug**
After playing the test build for a bit, the game will suddenly crash my PC

**To Reproduce**
Play the test build for any decent amount of time
1. Start up the game
2. Play around with the vehicles 
3. PC crashes

**Expected Behavior**
Game runs fine, PC doesn’t crash

**Desktop**

 - OS: Windows 10
 - Game Version: 20210808

**Additional context**
Whilst playing the game, everything seems to run relatively smoothly, even on the highest settings. Though I could be missing something obvious, the PC seems more than capable of handling this sorta thing.

**Comment by brikabrak** [comment]
What is a decent amount of time? What are the steps you take? Are you always on the highest system settings?

Please note the steps you've taken that has consistently produced this issue. If you have had crashes happen, you can fine crash dumps at C:/Users/username/AppData/Local/Temp/GHPC for any player and crash logs to post here.

Please note your general system specs (CPU, RAM, GPU) to give us an idea of your system.

**Comment by blake-bracerstudios** [comment]
What is a decent amount of time? What are the steps you take? Are you always on the highest system settings?

Please note the steps you've taken that has consistently produced this issue. If you have had crashes happen, you can fine crash dumps at C:/Users/username/AppData/Local/Temp/GHPC for any player and crash logs to post here.

Please note your general system specs (CPU, RAM, GPU) to give us an idea of your system.

**Comment by auggywoggy** [comment]
> What is a decent amount of time? What are the steps you take? Are you always on the highest system settings?
> 
> Please note the steps you've taken that has consistently produced this issue. If you have had crashes happen, you can fine crash dumps at C:/Users/username/AppData/Local/Temp/GHPC for any player and crash logs to post here.
> 
> Please note your general system specs (CPU, RAM, GPU) to give us an idea of your system.

**Comment by auggywoggy** [comment]
Basically, every time I actually play the game, it crashes my PC after 1-10 minutes of gameplay. Settings wise, I’ve tried lowering everything to the lowest possible settings, though the game *seems* to run fine even on the highest.

so basically

1. I start up the game
2. I try playing a mission
3. the game crashes my PC

This has happened every time I try to play. Also, I can’t seem to find any crash logs in the location you specified. 

Some general specs are

GPU: RX 480 8gb
CPU: i7-3770
RAM: 16gb DDR3 
OS: Win 10

**Comment by JoshBusuito** [comment]
GHPC crash logs (Player.log and output_log.txt) can be accessed here:

C:\Users\[USERNAME]\AppData\LocalLow\Radian Simulations LLC\GHPC

**Comment by auggywoggy** [comment]
These were the only two I found. I don't see an output_log.txt anywhere.

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/7028768/Player-prev.log)

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/7028766/Player.log)
