### ISSUE TITLE
Restocking 'all' ammo on M2 Bradley causes vehicle to lock up completely since T-62 update

### ISSUE THREAD

**Issue by Eddie894** [RadianSimulations/ghpc-feedback#242]
Restocking 'all' ammo causes vehicle turret to lock up indefinitely, driving controls also cease to function.

I am not playing with mods.

To reproduce, select the M2 Bradley with full ammo on both AP and HEI belts, go to restock and hit 'all'. Vehicle turret will lock up, which is normal for restocking, but for an indefinite amount of time. Driving controls also cease to function at this point. Attempting to 'cancel' the restock does not fix the turret or movement lock-up.

I would expect nothing to happen when attempting to restock all ammo with full belts.

I am using WIndows 11, GHPC version 20240219

**Comment by ProjoSix** [comment]
I have the same issue.  I replicated it twice playing Indomitable Investigation and using an M2. Game continues to run, but reloading stops, cannot be canceled.  Also, all movement controls freeze. 
I am running latest version of GHPC as of today. No mods. Windows 10
Will look to see if it happens in other Instant Actions, and/or at the range, but I think it will.

**Comment by ProjoSix** [comment]
Confirmed issue on Grafenwoehr range.

**Comment by bellatoretlegens** [comment]
Same problem here since new update

**Comment by Micromot20** [comment]
Can confirm, this bug has lost 2 missions for me already

**Comment by rexjuric** [comment]
Can confirm bug still present, vanilla, latest version, windows 10

**Comment by Eddie894** [comment]
Fixed as of version 20240312
