### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by sams-r27** [RadianSimulations/ghpc-feedback#243]
**Describe the bug**

Frequent crashing during campaign missions (may not be exclusive to campaign, I have not played any instant action missions lately)

**Are you playing with mods?**

No

**To Reproduce**
n/a

**Expected Behavior**

n/a

**Screenshots**

n/a

**Player Log**

[Player-prev(CRASH).txt](https://github.com/RadianSimulations/ghpc-feedback/files/14410215/Player-prev.CRASH.txt)
[Player(CRASH).txt](https://github.com/RadianSimulations/ghpc-feedback/files/14410216/Player.CRASH.txt)

**Sources**

n/a

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version: 20240219

**Additional context**

In both instances, crash occured at the exact moment a shot connected with an enemy. Both missions were defence missions. Also in both instances, crashes occured in the latter end of the mssion (many defeated enemies). I was also experiencing crashes yesterday but cannot comment what the game state was at the time. Crashes have not been this frequent before.

**Comment by brikabrak** [comment]
This issue has been greatly reduced in the latest version of the game, though it may still occur. Please update your game and try again.

**Comment by sams-r27** [comment]
I have noticed it runs well now since recent updates, but many thanks for
the reply regardless!

Sam
