### ISSUE TITLE
Minor visual discrepancies with vehicle models.

### ISSUE THREAD

**Issue by DarthMacVsoG** [RadianSimulations/ghpc-feedback#246]
Minor visual discrepancies with vehicle models.

I'm reporting these in particular as opposed to the typical "gun/antenna/whatever clipping through something else" since they seem small and might not be noticed.

#1 T-72M1 Visual Artifact:

The T-72M1 has what appears to be an extra smoke grenade support bar that, depending on turret rotation, will show as sticking out of the turret but it does not move with the turret and so is only sometimes visible when viewing the model.  The screenshot has the turret rotated to show this protruding through the DDR roundel to make it easier to spot.

![20240228172011_1](https://github.com/RadianSimulations/ghpc-feedback/assets/145851528/3a450f3c-d7b5-48b5-8b5b-e62084b91215)

#2 Pact tire models don't have a refined texture inside the wheel rim:

When viewing a vehicle model with a "tire hat" the texture inside the wheel rim is extremely low res/blurry (not tested on BRDM-2).

![20240228172045_1](https://github.com/RadianSimulations/ghpc-feedback/assets/145851528/ccc316ee-bee3-4281-a303-e108e512d12e)

#3 M60A3TTS Gunner's sight showing the same as on the M60A1 RISE Passive:

The turret top sight housing on the M60A3 TTS holds both the day and night (thermal) sights and this is visible when viewing it from outside the vehicle, as the night sight side has a distinct look compared to the day side.  I thought this was shown in a previous version but other differences between the M60 versions such as the cover for the laser rangefinder and the weather sensor are currently present so I could be wrong.

![20240228172220_1](https://github.com/RadianSimulations/ghpc-feedback/assets/145851528/8cb2fd07-51bb-4b27-b915-741fce5bb7c5)

![d531e52e07b97a51d59beaec41417f7e0235bc88](https://github.com/RadianSimulations/ghpc-feedback/assets/145851528/9f9e965b-a0e1-40f4-8fab-7271fcac72cb)

**Comment by brikabrak** [comment]
All known. All super low priority, but thanks for the heads up.
