### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by cptpatty** [RadianSimulations/ghpc-feedback#247]
**Describe the bug**

Played the campaign and also other modes game keeps on crashing few minutes in

**Are you playing with mods?**

no mods

**To Reproduce**

Played game it crashed, reopen game played it crashed again

**Expected Behavior**

game crash

**Screenshots**

**Player Log**

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/14569293/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/14569304/Player.log)

If the player log includes a reference to a crash.dmp file, you should attach that as well.
(crash.dmp file too large to upload)

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: Windows 11
 - Game Version 20240219

**Additional context**

**Comment by brikabrak** [comment]
Given the game has updated by this point with other optimizations, please update and try again. You can repost your issue if it is still happening.
