### ISSUE TITLE
CTD during Pushing Tin part 1 of 2

### ISSUE THREAD

**Issue by b0p1s** [RadianSimulations/ghpc-feedback#248]
**Describe the bug**

CTD during the middle of Pushing Tin part 1.

**Are you playing with mods?**

no

**To Reproduce**

Get a BMP2 to hit an M60 the right (or wrong?) way, I guess?

**Expected Behavior**

Game not CTDing when BMP2 engages M60 as Gorbachev intended

**Screenshots**

Wrong! Medal.TV clip. https://medal.tv/games/gunner-heat-pc/clips/20GOPZKzlT4hzu/d13370eontId?invite=cr-MSxVazksMjU3NjE5Nyw

**Player Log**

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/14582507/Player-prev.log)

**Sources**

Came to me in a dream? 

**Desktop (Please complete the following information):**

 windows 10
game vers 20240312

**Additional context**

I was able to complete the mission fine once, then it crashed after I replayed it. Have not since CTD'd while completing the mission.

**Comment by brikabrak** [comment]
Greatly reduced the occurrence of this issue.
