### ISSUE TITLE
T80 Smoke Grenade Salvo and game crashes

### ISSUE THREAD

**Issue by Gryphan1000** [RadianSimulations/ghpc-feedback#250]
**Describe the bug**

Smoke Grenade Salvo fires smoke grenades at an extreme range.  Something around 400 to 600 meters.   Additionally the game will crash regularly playing as a T80

**Are you playing with mods?**  NO

Yes or no. If yes, please note which mods here. Any third-party content may be incompatible with GHPC's ongoing updates. While issues related to third-party content are not a priority for development, known conflicts can be reported for other users.

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Player Log**

If this issue is regarding a crash or an issue during gameplay, please attach a Player.log file from the session where the issue occurred. The last two Player.log files generated during play sessions can be found here: `C:\Users\[USERNAME]\AppData\LocalLow\Radian Simulations LLC\GHPC`

If the player log includes a reference to a crash.dmp file, you should attach that as well.

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**Additional context**

**Comment by JoshBusuito** [comment]
Smoke grenade range is a historically accurate feature of Soviet tanks of the era.

The rest of the ticket is improperly formatted and provides no actionable information. We cannot do anything with a statement that the game crashes. Player logs and crash dump files are the minimum requirement for a useful crash report if reproduction steps are not available.

**Comment by Gryphan1000** [comment]
No it's not.  I know because I've seen it and used it.  I'm just pointing it out to help.  Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: JoshBusuito ***@***.***> Date: 3/14/24  2:06 AM  (GMT-06:00) To: RadianSimulations/ghpc-feedback ***@***.***> Cc: Gryphan1000 ***@***.***>, Author ***@***.***> Subject: Re: [RadianSimulations/ghpc-feedback] T80 Smoke Grenade Salvo and game crashes (Issue #250) 
Smoke grenade range is a historically accurate feature of Soviet tanks of the era.
The rest of the ticket is improperly formatted and provides no actionable information. We cannot do anything with a statement that the game crashes. Player logs and crash dump files are the minimum requirement for a useful crash report if reproduction steps are not available.

**Comment by JoshBusuito** [comment]
@Gryphan1000 If you have a source supporting your claims about the 3D6 grenade, please provide it.
