### ISSUE TITLE
Crash, computer restarts

### ISSUE THREAD

**Issue by RagnarTheTerrible** [RadianSimulations/ghpc-feedback#253]
Open GHPC, instant action, point alpha, hold the line.

After a few minutes, the game hard crashes and I get a BSOD. Stop Code: VIDEO_DXGKRNL_FATAL_ERROR

No mods

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/14782680/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/14782681/Player.log)

Windows 11
Steam Build ID 13762901

It happens on other missions as well.

**Comment by Waffle1434** [comment]
BSOD is usually a pretty low level hardware/driver issue. Highly recommended to update windows & drivers. It might be out of our control.

**Comment by RagnarTheTerrible** [comment]
Thanks for the quick response. I have done a bunch of things to try to fix this, including rolling back windows updates and drivers, removing the graphics card via system manager and reinstalling it with current drivers. It only happens when I'm playing Gunner Heat PC, which is why I'm reaching out here. If there is anything else you can think of I'd appreciate it. Otherwise I'll have to stop playing and try again at the next update.Thanks  againOn Mar 28, 2024, at 02:26, Waffle ***@***.***> wrote:﻿
BSOD is usually a pretty low level hardware/driver issue. Highly recommended to update windows & drivers. It might be out of our control.

**Comment by RagnarTheTerrible** [comment]
After your response I reached out to the manufacturer and after a back-and-forth I received a BIOS update. I've been testing, and so far no more crashes... I'll mark this as closed, and if anything else happens we will start over. Thank you for the quick reply and the suggestion!
