### ISSUE TITLE
Crash Report - It's back

### ISSUE THREAD

**Issue by RagnarTheTerrible** [RadianSimulations/ghpc-feedback#254]
During instant missions, I will experience a hard crash - BSOD with the VIDEO_DXGKRNL_FATAL_ERROR code, and the computer restarts.

I have uninstalled and reinstalled graphics drivers, scanned the memory, scanned the hard drive, checked for viruses and updated the BIOS. 

Running other resource heavy programs (flight sims) does not crash the computer.

No Mods

All I need to do is enter an instant mission and play. After some time the computer crashes.

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/14809510/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/14809511/Player-prev.log)

Windows 11
20240312.1

**Comment by brikabrak** [comment]
Update the game and reinstall your video drivers as the error in question is related to DirectX kernel errors.

**Comment by RagnarTheTerrible** [comment]
Hi Blake, thanks for the suggestion. I sent my computer in to the manufacturer to have it looked at and make sure there isn't an issue with the graphics card. When I get it back I'll try your suggestion (though I did uninstall and reinstall the drivers, it didn't work previously.)Thanks again!On Apr 14, 2024, at 10:00, Blake Farrugia ***@***.***> wrote:﻿
Update the game and reinstall your video drivers as the error in question is related to DirectX kernel errors.

**Comment by brikabrak** [comment]
Hopefully the machine gets fixed up for you. Closing this issue. If it continues to happen after you get your machine back, feel free to create another.

**Comment by RagnarTheTerrible** [comment]
Just got it back yesterday, I'll test it soon. Thanks!On Apr 29, 2024, at 15:35, Blake Farrugia ***@***.***> wrote:﻿
Closed #254 as completed.
