### ISSUE TITLE
Hanging at loading screen

### ISSUE THREAD

**Issue by Greyareaz** [RadianSimulations/ghpc-feedback#255]
**Describe the bug**

on launch the 'loading' screen hangs. GC kicks in and music from the intro screen starts but the loading screen remains unchanged. the app has to be closed to exit

**Are you playing with mods?**

no

**To Reproduce**

1. Go to steam
2. select 'play'

1. as above using desktop shortcut or steam folder app.exe

**Expected Behavior**

after loading screen GHPC update screen then intro screen

**Screenshots**

**Player Log**

If this issue is regarding a crash or an issue during gameplay, please attach a Player.log file from the session where the issue occurred. The last two Player.log files generated during play sessions can be found here: `[Player.log](https://gitIssue: Bug report
Let us know of any issues you've experienced playing the game. If this doesn't look right, choose a different type

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/14891129/Player.log)

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/14891126/Player-prev.log)

If the player log includes a reference to a crash.dmp file, you should attach that as well. If there is no crash dump located where the Player.log references it, check `%LOCALAPPDATA%\CrashDumps` and find the crash dump file corresponding to the application at the time the crash occurred.

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20240401

**Additional context**

completely remooved Steam and reinnstalled with the same problem

**Comment by brikabrak** [comment]
Bug in your log noting that the expected menu scene to be loaded does not exist, which points to a data issue. Try to install the latest patch 20240401.1 and see if your issues gets fixed.

**Comment by brikabrak** [comment]
As this is a data integrity issue, closing this.
