### ISSUE TITLE
T80 Suspension bug / Jumping Suspension

### ISSUE THREAD

**Issue by RealTimeyt** [RadianSimulations/ghpc-feedback#258]
**Describe the bug**

If the T80's suspension is driven into an object ( like the TOW launcher platform on Grafenwöhr ), the vehicle will get propelled upwards in a "jumping" motion.

**Are you playing with mods?**

No.

**To Reproduce**

1. Go to Grafenwöhr Range
2. Get in the T80
3. Drive into the TOW platform at an angle ( in a way that the suspension goes over the corner of the platform, might take multiple attempts ) 

**Expected Behavior**

Tank should not be "jumping"

**Screenshots**

https://github.com/RadianSimulations/ghpc-feedback/assets/131892235/94bb2aa6-1fd1-4589-a254-46fcb4dd541b

**Comment by brikabrak** [comment]
Known physics issue with T-80 and T72, probably others. Will get fixed eventually.
