### ISSUE TITLE
GAME CRASHES JUST 10 SECONDS AFTER OPENING

### ISSUE THREAD

**Issue by raghab1** [RadianSimulations/ghpc-feedback#259]
![image](https://github.com/RadianSimulations/ghpc-feedback/assets/166990087/e55c55a1-1fce-4185-b563-a79ab523bdeb)
THIS IS THE MESSAGE THAT POPS UP AFTER GAME CRASHES UPON OPENING
I HAVE TRIED MANY WAYS ALREADY AVAILABLE ONLINE
I AM A PREDATOR ACER LAPTOP USER AND I HAVE BEEN PLAYING THE GAME FOR 2 MONTHS NOW BUT THIS ISSUE STARTED AFTER THE APRIL FOOLS UPDATE. PLS I NEED HELP I DOWNLOADED FROM STEAM.

**Comment by brikabrak** [comment]
Try doing this again and reading the issue readme first. It will detail all the information you should provide so that we can try to assist.

**Comment by raghab1** [comment]
> Try doing this again and reading the issue readme first. It will detail all the information you should provide so that we can try to assist.

sorry my english is not so good i am using google translate for everything ok i will follow the issue readme
