### ISSUE TITLE
game crashes 10 seconds after loading

### ISSUE THREAD

**Issue by raghab1** [RadianSimulations/ghpc-feedback#260]
The game crashes upon launching

**Are you playing with mods?**
No

**To Reproduce**

1. launch the game
2. the game crashes/doesn't launch

**Expected Behavior**

The game will crash and message will appear, below is a screenshot of the same.

**Screenshots**
![Screenshot (2566)](https://github.com/RadianSimulations/ghpc-feedback/assets/166990087/4e02838e-b5a8-4cfd-868c-7ae94f6ec9a7)

**Player Log**

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/15011024/Player.log) 

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/15011026/Player-prev.log)

latest crash reports
[crash.dmp](https://github.com/RadianSimulations/ghpc-feedback/files/15011116/crash.dmp)

[crash.dmp](https://github.com/RadianSimulations/ghpc-feedback/files/15011121/crash.dmp)

**Desktop (Please complete the following information):**
- OS: - windows 11
 - Game Version - 20240401.1

**Comment by brikabrak** [comment]
Your logs end without any explicit detail, and one of your crash dumps points to nvwgf2umx, which is an nvidia library. The other gives no actual information about the crash.
Do you happen to have your system overclocked in gpu/ram/cpu?

**Comment by raghab1** [comment]
> Your logs end without any explicit detail, and one of your crash dumps points to nvwgf2umx, which is an nvidia library. The other gives no actual information about the crash. Do you happen to have your system overclocked in gpu/ram/cpu?

No I haven't done any overclocking in gpu/ram/cpu .this game is pretty much the only thing i played and it functioned well until the issue started.

**Comment by raghab1** [comment]
I was laid off last month and this game helped me pass time easy and therefore i want it to be fixed desperately.

**Comment by brikabrak** [comment]
Sorry to hear about that. What is your GPU?
Also, if you haven't already, please try verifying your game files, and if that does not help, see if reinstalling the game helps.

**Comment by raghab1** [comment]
i have tried everything man i think god doesnt want me to have any fun at all perhaps. i tried repurchasing via a new account but that also showed the same error when i launched the game. I firmly believe something is truly wrong with my laptop.

**Comment by raghab1** [comment]
hey brik today i installed steam after a good while and guess what the game has started working again, i am sooooooo happy i am resolving this issue for now
