### ISSUE TITLE
Incorrect color filter gunner sight for T-72/64/80 tanks + sound effects 

### ISSUE THREAD

**Issue by Ramon51rus** [RadianSimulations/ghpc-feedback#264]
**Describe the bug**

In this topic I want to report the incorrect operation of color filters on Soviet tank sights

**Are you playing with mods?**

No

**To Reproduce**
All time 

**Expected Behavior**

Gunner sight T-72 
![GfQpYI2Nl4g](https://github.com/RadianSimulations/ghpc-feedback/assets/168218111/717b4636-19c4-4765-9aa5-adb845d999ac)
![YuAou2-ZuP0](https://github.com/RadianSimulations/ghpc-feedback/assets/168218111/29ae4705-71c8-42e2-ad90-c2d91c60f5fc)
Gunner sight T-64
![hq720](https://github.com/RadianSimulations/ghpc-feedback/assets/168218111/e2a39557-c984-4c6c-9179-54590b96688a)

**Screenshots**

**Player Log**

If this issue is regarding a crash or an issue during gameplay, please attach a Player.log file from the session where the issue occurred. The last two Player.log files generated during play sessions can be found here: `C:\Users\[USERNAME]\AppData\LocalLow\Radian Simulations LLC\GHPC`

If the player log includes a reference to a crash.dmp file, you should attach that as well. If there is no crash dump located where the Player.log references it, check `%LOCALAPPDATA%\CrashDumps` and find the crash dump file corresponding to the application at the time the crash occurred.

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**Additional context**

**Comment by JoshBusuito** [comment]
Color filters on Soviet sights are usually removable, and their intensity is a matter of artistic depiction. We do not consider this a bug, and it will not be worked on.
