### ISSUE TITLE
visual hole in m60a3 betwen engine compartment and turret hull roof

### ISSUE THREAD

**Issue by JaWi3011** [RadianSimulations/ghpc-feedback#274]
**visual hole in m60a3 betwen engine compartment and turret hull roof**

it is a hole on the right side of the engine compartment hull roof, you can only see it when the turret is facing to a side.

**no mods**

Yes or no. If yes, please note which mods here. Any third-party content may be incompatible with GHPC's ongoing updates. While issues related to third-party content are not a priority for development, known conflicts can be reported for other users.

**To Reproduce**

1. Go to 'any map with m60a3 it also works in showcase'
2. 'go to m60 and turn its turret to the side'
3.  'use a vehicle i used t64 because it has a good hight'
4. See hole

**a hole you see trough**

**Screenshots**

![20240607211426_1](https://github.com/RadianSimulations/ghpc-feedback/assets/172105945/d52c1262-a9c2-4cc9-a096-c68913f5c97e)
![20240607211429_1](https://github.com/RadianSimulations/ghpc-feedback/assets/172105945/3cca96db-deb8-4c21-93fa-bcbf7494fee4)

**Player Log**

If this issue is regarding a crash or an issue during gameplay, please attach a Player.log file from the session where the issue occurred. The last two Player.log files generated during play sessions can be found here: `C:\Users\[USERNAME]\AppData\LocalLow\Radian Simulations LLC\GHPC`

If the player log includes a reference to a crash.dmp file, you should attach that as well. If there is no crash dump located where the Player.log references it, check `%LOCALAPPDATA%\CrashDumps` and find the crash dump file corresponding to the application at the time the crash occurred.

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**i stumled across the problem in a mission**

it is another problem but when i drove the uaz with about 40kph in a tank the came crashed

**Comment by JoshBusuito** [comment]
This was resolved in the M60 variants update.
