### ISSUE TITLE
Predator vision when tanks moving "behind" foliage, TAA only?

### ISSUE THREAD

**Issue by rossmum** [RadianSimulations/ghpc-feedback#28]
**Describe the bug**

There's a slight shimmering silhouette of a tank visible (just barely) as it moves behind vegetation. Issue seems to be tied to TAA as I tried to reproduce with all other AA settings (including none) and was unable to. It's very faint, but it's enough to maintain accurate lead on a tank that's been completely terrain/foliage masked for more than 20 seconds.

**To Reproduce**

1. Enable TAA 
2. Launch M60A3 wave (this is where I noticed it and probably the fastest way to see it in action)
3. Immediately drive to the second treeline on the right, so you don't die immediately and are looking through multiple layers of foliage
4. Wait for the first dust trails to appear. Pick one, track it with the day sight. Zoom as necessary.
5. Watch in amazement as a faint, shimmering silhouette of the tank remains visible even as it dips into the dead ground by the left forest, or passes behind multiple rows of bushes (tree trunks and bushes right next to your own tank can still mask this).
6. Demonstrate the superiority of Soviet ~~wallhacks~~ optical sighting technology by sniping that capitalist pig dog as soon as he dares leave dead ground, even though he can't see you and you sure shouldn't be able to see him.

**Expected Behavior**

Tank silhouettes not visible when obstructed by foliage (and especially actual terrain).

**Screenshots**

Impossible to demo in screenshots, as it looks like some kind of interlacing effect caused by TAA interacting with moving objects is the underlying cause. Here's a video, I doubt you'll be able to see what I mean through youtube compression though -

https://www.youtube.com/watch?v=vvHKEf-2bWs

**Desktop (Please complete the following information):**

 - OS: W10 Home 20H2
 - Game Version 20210907.1

**Additional context**

I swear to god I'm not hallicinating. I'm not off my meds. Please believe me.

**Comment by Waffle1434** [comment]
Unfortunately this is a known Unity Engine level bug, when motion vectors are rendered (TAA or motion blur), they often render in the wrong order resulting in wallhacks. The only current solution is to disable dynamic batching, but that hurts performance.
