### ISSUE TITLE
M774 APFSDS Sell Shattered 

### ISSUE THREAD

**Issue by NikolaiBolas** [RadianSimulations/ghpc-feedback#280]
**Describe the bug**
I was in the campaign on the NATO side playing with the M1. The mission was set in the Fulda Gap. The mission was to to raid Pact force at a staging area. I used M774 APFSDS and got a non pen on side armor of what I believe to be a T-64A. In the top right coroner of the screen it said the round shattered do to impact angle. However to my perception the impact of the round it was around 90 degrees to the side.

**Are you playing with mods?**
No

Yes or no. If yes, please note which mods here. Any third-party content may be incompatible with GHPC's ongoing updates. While issues related to third-party content are not a priority for development, known conflicts can be reported for other users.

**To Reproduce**
I don't know how to reproduce this since it was in the campaign and not instant action. As mentioned above I took a side shot an a T-64a with M774 and the round shattered on a side plate of armor that was at 90 degrees to the round at point of impact.

**Expected Behavior**

**Screenshots**
![Screenshot (129)](https://github.com/RadianSimulations/ghpc-feedback/assets/175284894/393c85e5-2a83-409b-a1ab-1f76e2194758)
![Screenshot (130)](https://github.com/RadianSimulations/ghpc-feedback/assets/175284894/da0942ac-8765-480b-bff8-d24a5529842c)
![Screenshot (131)](https://github.com/RadianSimulations/ghpc-feedback/assets/175284894/c494f598-9df1-469c-9b72-c38492630133)
![Screenshot (132)](https://github.com/RadianSimulations/ghpc-feedback/assets/175284894/33d57ad7-fe23-4fff-bed6-dcffa374fb78)
(first bug report don't know if the screenshot uploaded properly)

**Player Log**

If this issue is regarding a crash or an issue during gameplay, please attach a Player.log file from the session where the issue occurred. The last two Player.log files generated during play sessions can be found here: `C:\Users\[USERNAME]\AppData\LocalLow\Radian Simulations LLC\GHPC`

If the player log includes a reference to a crash.dmp file, you should attach that as well. If there is no crash dump located where the Player.log references it, check `%LOCALAPPDATA%\CrashDumps` and find the crash dump file corresponding to the application at the time the crash occurred.

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS:  Windows 10
 - Game Version 20240710

**Additional context**

**Comment by HankoDobringer** [comment]
Not a bug. T-64 has a large angled section on the hull right about there so this was not a flat hit.
