### ISSUE TITLE
M1 Side Armor Hole

### ISSUE THREAD

**Issue by canon545** [RadianSimulations/ghpc-feedback#281]
**Describe the bug**
I was in the campaign playing a defense mission. After all my T-80's were eliminated, I decided to use the BTR-70's to rush the final immobile Abrams. I shot at the Abrams' side, and a 14.5mm round went through the side armor of the Abrams, killing the gunner and knocking it out. 

**Are you playing with mods?**
No.

Yes or no. If yes, please note which mods here. Any third-party content may be incompatible with GHPC's ongoing updates. While issues related to third-party content are not a priority for development, known conflicts can be reported for other users.

**To Reproduce**
Because this happened during a campaign mission, and there is no test range for the BTR-70, but judging from my screenshot, you should be nearly or exactly parallel with the Abrams' side, and aim for the top right corner of where the second and third side plates meet. I will also include a YouTube link to a clip with the moment.

**Expected Behavior**

**Screenshots**
Clip:
[Youtube Video](https://www.youtube.com/watch?v=_t3JdeKgzhM)

![Screenshot_13](https://github.com/user-attachments/assets/154fb8a0-3780-4bf3-b7d2-0aaa09b0d596)

**Player Log**

If this issue is regarding a crash or an issue during gameplay, please attach a Player.log file from the session where the issue occurred. The last two Player.log files generated during play sessions can be found here: `C:\Users\[USERNAME]\AppData\LocalLow\Radian Simulations LLC\GHPC`

If the player log includes a reference to a crash.dmp file, you should attach that as well. If there is no crash dump located where the Player.log references it, check `%LOCALAPPDATA%\CrashDumps` and find the crash dump file corresponding to the application at the time the crash occurred.

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: Win 11
 - Game Version: 20240710

**Additional context**

**Comment by JoshBusuito** [comment]
In order for this to be considered a bug, there needs to be proof that the expected behavior is different. In this case, that means you need to demonstrate that the real life armor thickness and performance of the base model Abrams in that location would not allow a 14.5mm round to enter. If you have such proof, re-open the issue and present it. As noted in the prompt, "this doesn't feel right" is not a valid bug report reason.
