### ISSUE TITLE
T80B/T64B FCS No Auto Elevation Lead

### ISSUE THREAD

**Issue by xuzhiren023** [RadianSimulations/ghpc-feedback#285]
**Describe the bug**

T80B/T64B's FCS suppose to auto lead in both horizontal and vertical. However right now it's just horizontal, greatly reduce its effectiveness when shooting cross terrain on moving targets.

**Are you playing with mods?**

No

**To Reproduce**

Using T64B/T80B
Tracking a target when target is going through stable elevation change
Round supposed to land on target but missed

**Expected Behavior**

FCS can auto lead target even if target position changed vertically.

**Screenshots**

n/a

**Player Log**

N/A

**Sources**
There is a youtuber mentioned this problem is his playthrough video. He explain the correct behavior in video description.
The youtuber is a current (or just retired) M1A2 SEP2 Tank Commander
"A FCS just like my SEP V2, how ever there seems to be improper tracking between the gun and the optics. The Azimuth tracking is spot on, but the elevation tracking needs to be worked on. With the automatic lead its literally put the reticle on target, track it, lase, and pull the trigger and it should hit."

https://youtu.be/tUYVyAJiinU
https://youtu.be/IM4AtoGeb3M

**Desktop (Please complete the following information):**

n/a

**Additional context**

n/a

**Comment by JoshBusuito** [comment]
Hello, please provide a source stating that the 1A33 fire control system should apply automatic lead in the vertical direction. The videos you linked do not demonstrate this, as this Abrams commander is not qualified to know the technical details of a Soviet tank.

**Comment by xuzhiren023** [comment]
> Hello, please provide a source stating that the 1A33 fire control system should apply automatic lead in the vertical direction. The videos you linked do not demonstrate this, as this Abrams commander is not qualified to know the technical details of a Soviet tank.

Hi Josh,
Sorry, that's the only source I have now. If this is the correct behavior for 1A33 then I have no further comments on this. Please feel free to close this issue. Thanks.
