### ISSUE TITLE
BMP-1 turret rotates to the left slightly after firing 2A28 Grom

### ISSUE THREAD

**Issue by Jaeger1863** [RadianSimulations/ghpc-feedback#29]
BMP-1 turret rotates to the left to a very minor increment after firing 2A28 Grom at a target. This can be observed both through the sight or throught the third person view.

**To Reproduce**

1. Go to Proving Grounds
2. Select BMP-1
3. Fire 2A28 Grom
4. Observe turret rotation afterwards

**Expected Behavior**

Turret does not rotate without any input from the player.

**Comment by Jaeger1863** [comment]
It actually rotates in both directions, so far i can't say what determines the direction of rotation.

**Comment by Jaeger1863** [comment]
It's the hull rotating after a shot, not the turret itself which i believe is already a known issue.

**Comment by alqiwa** [comment]
behaviour still occurs as described
