### ISSUE TITLE
HEAT for the T-64R not exploding

### ISSUE THREAD

**Issue by badatcodingbean** [RadianSimulations/ghpc-feedback#291]
**Describe the bug**

1 instance of HEAT not exploding once hitting BRDM-2

**Are you playing with mods?**

No

**To Reproduce**

1. Go to Patton pass
2. Drive and fire upon BRDM-2, aim at the headlights
3. See AAR
4. See That the HEAT didnt explode and didn't ricochet

**Expected Behavior**

HEAT either exploding or ricocheting off the vehicle

**Screenshots**
![20240808143535_1](https://github.com/user-attachments/assets/5fd8c0cc-9878-4bf8-81cc-1288bfadbd49)
![20240808143726_1](https://github.com/user-attachments/assets/ac9f4e1e-1560-42a8-8726-e5188a27289c)
![20240808143728_1](https://github.com/user-attachments/assets/3ae2b3f8-c2a9-4e6e-a106-6b445bbef5b8)
![20240808143740_1](https://github.com/user-attachments/assets/972d6529-1b55-4328-9ad1-3211eabe81d3)
**Player Log**

N/A

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20240806

**Additional context**

Was the only instance of this happening, could just be a random bug

**Comment by JoshBusuito** [comment]
As clearly indicated in the red damage log for the shot (upper right corner of the screen), the round was crushed as it impacted the target, due to the angle of the armor. This prevented it from properly forming a penetrator jet when it detonated. This is not a bug.

**Comment by badatcodingbean** [comment]
> As clearly indicated in the red damage log for the shot (upper right corner of the screen), the round was crushed as it impacted the target, due to the angle of the armor. This prevented it from properly forming a penetrator jet when it detonated. This is not a bug.

Shouldn't shrapnel be formed from the explosion causing damage to any optical equipment though?

Thank you for your hard work on the game too :)

**Comment by JoshBusuito** [comment]
No, only for munitions with frag sleeves built in.
