### ISSUE TITLE
M60A1 AOS Armor not Armoring

### ISSUE THREAD

**Issue by DarthMacVsoG** [RadianSimulations/ghpc-feedback#293]
**Describe the bug**

M60A1 AOS destroyed by BTR-60PB at 2100+ meters.

A 14.5mm KPVT machine gun round passed through the front hull and knocked out the tank.  I don't recall it burning but the crew did bail out.  At first I thought it was lucky SPG-9 hit but after reviewing the AAR I found that the machine gun round was what did it as that was the only recorded weapon impacting the tank until the hatches popped open.  Don't know if it matters but it was less than 10 or so shots that actually hit the tank and all but a couple were before the one that knocked it out.

One point of interest is that the damage log does not state the armor and projectile had any interaction at all other than the hull stopping it on the way out.  The first entry is "Entered fighting compartment" and not "Hit _____" or "Penetrated _____" so it reads as if the round just passed through the hull front and the line indicating projectile path doesn't change color to indicate projectile fragments or spalling, just plain white as normal for the projectile path.

**Are you playing with mods?**

No.

**To Reproduce**

Blast the front of an M60A1 AOS with a KPVT and say "Wut RHA doing?"

Seriously though I'll see if I can try and reproduce this again on the range and update if successful.

**Expected Behavior**

Armor not having a "Bruh" moment.

**Screenshots**

![20240808153524_1](https://github.com/user-attachments/assets/5d72410d-6182-48a6-81f1-35a519bcdd28)

![20240808153531_1](https://github.com/user-attachments/assets/0bc940eb-298f-405e-b6f7-62363cbf504f)

![20240808153546_1](https://github.com/user-attachments/assets/c98b6d9d-e81c-42cc-aa01-690fd04eb495)

**Player Log**

Unfortunately I was playing with my kid and didn't copy out the player log before it was overwritten.

Bad playtester, bad...no M551 for you!

**Sources**

Like physics and stuff.

**Desktop (Please complete the following information):**

 - OS: Win 10 Pro 22H2
 - Game Version 20240806

**Additional context**

As always y'all are doing a great job, love the retro content in the latest update!

**Comment by JoshBusuito** [comment]
According to the damage log on the upper right of the screen, the round didn't detect any armor before entering the compartment. I've verified the M60A1 AOS armor is functioning normally, so this looks like a case of an old bug where rounds can fail to detect armor - not related to this tank in particular. We're already tracking that one so I'm going to close this. Thanks for the report.
