### ISSUE TITLE
planes commiting self death

### ISSUE THREAD

**Issue by panikoUwU** [RadianSimulations/ghpc-feedback#299]
**Describe the bug**

Planes passing through terrain when you call Fixed-wing CAS on your location

**Are you playing with mods?**

No

**To Reproduce**

1. Go to any mission with Fixed-wing CAS available
2. Call a Fixed-wing CAS on your location
3. Wait for CAS to come
4. See them remember their Japanese roots

**Expected Behavior**

CAS simply destroying me instead of themselves

**Screenshots**

![image](https://github.com/user-attachments/assets/7e30969a-8d38-4e10-adf8-691c230e2c73)
![suicidal](https://github.com/user-attachments/assets/aca235ae-25f1-451a-983e-02bc53634141)
![suicidal2](https://github.com/user-attachments/assets/fbddb951-abe1-4c3f-b491-1690d9a24b60)

**Player Log**

[Player.log](https://github.com/user-attachments/files/16649267/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16649268/Player-prev.log)

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version: 20240806

**Additional context**

CAS ended itself when I wanted to end myself

**Comment by JoshBusuito** [comment]
Fixed in version 20241124
