### ISSUE TITLE
The armour of M60 was missing

### ISSUE THREAD

**Issue by FriedDuofold** [RadianSimulations/ghpc-feedback#303]
**Describe the bug**

A OF350 penetrated the turret of M60, entered the fighting compartment and finnally exploded after hitting the ammo.
The white trace went through the turret
**Are you playing with mods?**

No
**Screenshots**
![1705180_33](https://github.com/user-attachments/assets/7579c6a6-c082-441c-b695-cbf452e90c8f)

**Desktop (Please complete the following information):**

 - OS: Windows 11
 - Game Version 20240806

**Comment by JoshBusuito** [comment]
Covered by #307
