### ISSUE TITLE
M113 frontally penetrating and killing a T-55A with an M2 Browning .50

### ISSUE THREAD

**Issue by vvollpp** [RadianSimulations/ghpc-feedback#306]
**Describe the bug**

An M113 can apparently frontally pen a T-55A. In the mission "Pragmatic Payment part 2 of 3", I've been penetrated in the side armor at an extreme angle (since I wasn't entirely facing the M113 completely) by an M113's Browning .50 cal. The M113, somehow, penetrated, and the .50 cal went through the driver's leg and waist, the gunner's knee, upper leg and pelvis, through the propellant casings in front of the engine deck, through the engine firewall and into the engine, making the tank catch fire and resulting in the crew bailing out.

**Are you playing with mods?**

No, I'm using the current Steam version unmodded.

**To Reproduce**

I don't think this is easily reproducible. It either is a tiny pixel of armor modeled incorrectly or some other bug. I'll just list what I did.

1. Go to Instant Mission "Pragmatic Payment part 2 of 3" (Fulda Outskirts)
2. In the T-55A, drive forward until you reach the 3rd M113. It's 2 (or 3, not sure) M113s in one place on the left side of the mission's spawn. The left one of the two visible M113s is the one that killed me (as seen in the last screenshot)
3. Get (un)lucky and be somehow killed be a .50 cal in your Russian tank.
5. See error

**Expected Behavior**

I didn't expect to get killed by a M113's M2 Browning in my tank.

**Screenshots**

![image](https://github.com/user-attachments/assets/fa17ee4f-db86-46f4-aab4-0a862643cb59)
![Screenshot 2024-09-29 162027](https://github.com/user-attachments/assets/5391f3ff-c8c9-4839-acca-1df42f51a916)
![Screenshot 2024-09-29 162017](https://github.com/user-attachments/assets/aedce9b6-b88c-4c4b-85ca-c686dbc16aba)
![Screenshot 2024-09-29 162103](https://github.com/user-attachments/assets/a8e41963-915e-4b7c-a4bf-b65bb3615b13)
![Screenshot 2024-09-29 162048](https://github.com/user-attachments/assets/8946b391-ab4b-496d-b74b-e2caf5031587)

**Player Log**

I hope this is the correct file.
[Player.log](https://github.com/user-attachments/files/17179563/Player.log)

**Sources**

> If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
> Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

I know it says above "This doesn't feel right" isn't valid, but I don't think I need a proper source to report this. To put it in other words: This doesn't feel right. Highly doubt a T-55A should be killable by a .50 cal at all, let alone frontally at this angle.

**Desktop (Please complete the following information):**

 - OS: Win11
 - Game Version: 20240806

Apologies if this isn't explained well enough or something like that. I'm not good at explaining things.
Hopefully, this bug report is still helpful

**Comment by vvollpp** [comment]
If there's more info or data you need, just let me know

**Comment by JoshBusuito** [comment]
This appears to be a case of a rare, known issue where a shot can fail to detect armor. It is not related to a specific vehicle or armor layout. For convenience, I've created #307 to point back to for this and future instances. Thanks for the report.

**Comment by vvollpp** [comment]
Ah, okay, I see. Thanks a lot for explaining what happened. Glad I was able to at least provide another example
