### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Willyakake** [RadianSimulations/ghpc-feedback#308]
**Describe the bug**

**Are you playing with mods?**

No

**To Reproduce**

**Expected Behavior**

The game to not crash and just keep playing? 

**Screenshots**

Is not needed i just get an black screen. 

**Player Log**

d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: failed to create buffer (target 0x2 mode 1 size 6144) [0x887A0005]
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: failed to create buffer (target 0x1 mode 1 size 327680) [0x887A0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
No smoke column origin set! Assigning a fallback...
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: attempt to lock null buffer
d3d11: EndWrite on null buffer
d3d11: failed to create buffer (target 0x2 mode 1 size 20480) [0x887A0005]
d3d11: attempt to lock null 
Crash!!!!

**Additional context**

I can play about 10-20 minutes in an mission before my screen gets black then the game crashes i dont know why.

**Comment by brikabrak** [comment]
Please post a full player log and a crash dump if you have one, as well as your system specs. Note if this is a recent development or if you just picked up the game and tried playing.

Without more information. these errors are generally from drivers or hardware. Normally it is out of scope for us to troubleshoot. Would recommend latest graphics drivers, verify steam files, and reinstall if it persists.
