### ISSUE TITLE
BTR rounds fired towards player tank are silent

### ISSUE THREAD

**Issue by 6komodo6** [RadianSimulations/ghpc-feedback#313]
**Describe the bug**

No audio for BTR rounds going off near player's tank
**Are you playing with mods?**

No

**To Reproduce**

Face off against any BTR and its rounds going over you or near you will be silent

**Expected Behavior**

Rounds whizzing past or some audio feedback

**Screenshots**

https://streamable.com/xijest

**Comment by JoshBusuito** [comment]
This board is intended for reporting legitimate bugs in the game. It is not a venue to request new features. Audio cues for bullet pass-bys are not a feature in the game, so they are not an appropriate subject for an issue report.
