### ISSUE TITLE
Ural Truck goes Weeee

### ISSUE THREAD

**Issue by Toxi2202v2** [RadianSimulations/ghpc-feedback#37]
**Describe the bug**

**To Reproduce**

1. Go to 'fun Drive'
2. Get inside 'The new Ural truck'
3. Start Driving get somespeed(around 20kmh) 'Then Spam C button for view Change'

**Expected Behavior**

The Truck should start Flying if you keep Spaming C.

**Screenshots**
[https://cdn.discordapp.com/attachments/751138720639615118/895388061486178344/2021-10-06T190458.png](url)

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10] <----(I have a Windows 10 PC)
 - Game Version [e.g. 20210506.1]

**Additional context**

**Comment by brikabrak** [comment]
Fixed as part of October build.
