### ISSUE TITLE
9K14 flare bug

### ISSUE THREAD

**Issue by Kingrora** [RadianSimulations/ghpc-feedback#38]
**Describe the bug**

The flare on the 9K14 missile stays visible when the missile is behind objects

**To Reproduce**

1. Go to bmp1
2. fire the missile then guide it behind a building or a hill
3. the missile will go behind the object but the flare will remain visible

**Expected Behavior**

Flare should derender/disappear like the missile

**Screenshots**

![image](https://user-images.githubusercontent.com/85451404/136637614-3f286033-eb9f-47ab-a848-169c184d5759.png)

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version [e.g. 20211004.1]

**Additional context**

https://user-images.githubusercontent.com/85451404/136637728-bc56239f-c567-4a8a-b704-f837f81cc543.mp4

**Comment by blake-bracerstudios** [comment]
Not priority.
