### ISSUE TITLE
Rounds facing the wrong way when pausing

### ISSUE THREAD

**Issue by Kingrora** [RadianSimulations/ghpc-feedback#4]
**Describe the bug**
When pausing the simulation while a shot has been fired the round will change direction where it is frozen in place and the tracer will become much longer than it probably should be. Also, the shell will flatten out when paused. For example, if the round was fired 20 degrees into the sky instead of the round appearing to be 20 degrees relative to the ground it will instead be 0 degrees (flat) relative to the ground. (images Supplied)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a mission
2. Fire any round
3. Pause the game using 'P'
4. Find the round that was fired

**Expected behaviour**
What is expected to happen is to see the shell on the trajectory and direction it was fired from.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 202010505.1

**Additional context**
The images supplied will help understand the issue
![Untitled-1](https://user-images.githubusercontent.com/85451404/120948974-55b73500-c73b-11eb-8d5d-34bf9642e9a0.jpg)
![Untitled-2](https://user-images.githubusercontent.com/85451404/120948979-56e86200-c73b-11eb-8516-36392a817ebb.jpg)

**Comment by JoshBusuito** [comment]
I believe this is related to the routine that updates rounds' direction.  It must be running one time too many when the game is paused, which gives it a displacement of 0 and reverts the vector to Vector3.zero (directly north).

**Comment by Waffle1434** [comment]
Fixed in dev build
