### ISSUE TITLE
Gunner sight doesn't appear

### ISSUE THREAD

**Issue by Lyncesca** [RadianSimulations/ghpc-feedback#43]
![ss (2021-11-14 at 03 00 39)](https://user-images.githubusercontent.com/6898670/141665882-aced8458-8786-4106-a7bd-b2ff2f0803ec.png)
No clue what would even cause this. Updated to newest version, pressing shift doesn't bring up gunner optics.

**Comment by Waffle1434** [comment]
Ah crap. Would help a lot if you could obtain the game's log if this happens again (`%USERPROFILE%\AppData\LocalLow\Radian Simulations LLC\GHPC\output_log.txt`).

**Comment by JoshBusuito** [comment]
Fixed by RadianSimulations/GHPC-vertical#1249
