### ISSUE TITLE
M923 bugged suspension dynamics ("rodeo")

### ISSUE THREAD

**Issue by vedurk** [RadianSimulations/ghpc-feedback#48]
**Describe the bug**

After a jump into the pit in the proving ground at speed, M923 seemed to jolt around quite a bit. The jumping had continued even when there was no significant speed left.

**To Reproduce**

1. Open the Proving Ground scenario
2. Take M923
3. Gain some speed
4. Cut through the forest and the small hill in it (next to M1IP)
5. Jump into the last pit at around 45 km/h
6. Rodeo

**Expected Behavior**

The truck to dig itself into the ground or to have it slide forward and not jump around.

**Screenshots**

A video:

https://user-images.githubusercontent.com/51442956/145120224-ee407c7f-9f7d-42aa-a788-d01c71fe66b6.mp4

**Sources**

"This doesn't feel right"

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version: Patreon 20211106.1

**Additional context**

Doesn't seem to happen with the Ural

**Comment by JoshBusuito** [comment]
Suspension has improved since this was posted, and this should be much less of a thing now.
