### ISSUE TITLE
M60A3 TTS barrel twitching when switching between weapons (also when gunner and commander killed)

### ISSUE THREAD

**Issue by vedurk** [RadianSimulations/ghpc-feedback#49]
**Describe the bug**

Cycling through the different weapons, the barrel twitches up and/or down. Happens also when both the gunner and the commander are dead (reproducing in killing only them is quite difficult but I had a video from a scenario).
The problem seems to occur mostly between the 7.62 MG and the main gun, but can be also between the 7.62 MG and the .50 cal.

**To Reproduce**

1. Use a M60A3 TTS
2. Cycle through all 3 weapons with "]" or "["
3. Observe the barrel twitching

**Expected Behavior**

The barrel should be still (at least when the gunner and the commander are non-functional)

**Screenshots**

Video:

https://user-images.githubusercontent.com/51442956/145127617-177c7ea6-518a-4a4c-bc23-6fe1724038b2.mp4

Video (with the commander and the gunner dead):

https://user-images.githubusercontent.com/51442956/145127711-4bac8345-7441-4726-aec2-85f9851aed32.mp4

**Sources**

"This doesn't feel right"

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version: 20211106.1

**Additional context**

–

**Comment by JoshBusuito** [comment]
The fire control system is set to 1200 meters.  The vertical compensation (superelevation) required for 7.62 bullets at that range is much more than for main gun rounds.  When you switch weapons, the gunner indexes for the correct one, causing the barrel to move despite the gunner's aim point remaining the same.

**Comment by vedurk** [comment]
I see. But this shouldn't happen with the gunner dead?

**Comment by JoshBusuito** [comment]
I'll make a change so the control won't work with a dead gunner.
