### ISSUE TITLE
Game immediately closes after opening and deletes the EXE file after opening.

### ISSUE THREAD

**Issue by Ra4ndomUser** [RadianSimulations/ghpc-feedback#53]
**Describe the bug**
Game EXE deleting itself whenever opening the game
Opening the game will cause it to close automatically and delete the EXE file of GHPC.
**To Reproduce**
Open the game
1. Go to 'itch.io app'
2. Click on 'Launch game'

**Expected Behavior**
Game immediately closes after opening.
Expected the game to launch
**Screenshots**

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**Additional context**

**Comment by JoshBusuito** [comment]
If you have any antivirus software installed on your system, you may need to add GHPC as an exception to it.  This behavior is not normal and I don't think we can do anything about it from our end.
