### ISSUE TITLE
Player that has done the main gun not firing bug from US tanks can affect the "loader AI" of other Voiced Tanks if switched into unaffected vehicles

### ISSUE THREAD

**Issue by Lotusen** [RadianSimulations/ghpc-feedback#55]
**Describe the bug**
The main gun does not fire after the loader loaded a round but does not say up causing the gun to be not fired at will, this happens when changing the vehicle you are in to another before the roll call queue of the tank is not heard but will not affect AI control over all the functions of the tank if not switched into one

**To Reproduce**

1. Go to proving grounds 
2. switch to the M1IP before the M60A3 crew does a roll call
3. go to the range and fire
4. wait for the round to load again and see if the loader says "Up!"
5. if none this is the bug but if you heard "Up!" repeat the steps again
6. If familiarized, go to Hold The Line Mission or any US tanks on a mission
7. do step 2 again but this time switch to the ATGM guy and no more 
8. the tank you are spawned in will not be able to fire after reloading the gun while the other M60A3 will be able to fire off the rounds unless tabbed/switched into causing to have the same problem the other tank had that you spawned in.

**Expected Behavior**

1. The main gun should fire

https://user-images.githubusercontent.com/93954888/146880133-c25f37de-8d0d-44d8-af0d-3304ce4918b3.mp4

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20211208

**Comment by vedurk** [comment]
Seems to be equivalent to https://github.com/RadianSimulations/ghpc-feedback/issues/52 ?
