### ISSUE TITLE
Setting waypoints for automated movement is not working

### ISSUE THREAD

**Issue by Lotusen** [RadianSimulations/ghpc-feedback#59]
**Describe the bug**

Setting a waypoint to where you want to go will not work and It traces a path that is not corelated to the player's position 

**To Reproduce**

1. Go to any mission
2. press button for Set Waypoint
3. set it to where you want to go

**Expected Behavior**

setting a waypoint should drive you to your desired destination

**Screenshots**

![2022-02-01](https://user-images.githubusercontent.com/93954888/151929625-4d71a356-c1e2-4f3d-8cdb-923b7bda6698.png)

https://user-images.githubusercontent.com/93954888/151930321-0c85045a-3818-4a4e-aea1-af9930bc6ac5.mp4

![2022-02-01 (2)](https://user-images.githubusercontent.com/93954888/151930442-55c94568-55af-47bf-ac26-70d799fd2a9c.png)
![2022-02-01 (3)](https://user-images.githubusercontent.com/93954888/151930485-eb9904d2-03a7-447d-aeab-ff83032cd238.png)
![2022-02-01 (1)](https://user-images.githubusercontent.com/93954888/151930509-757dfcd7-2083-477f-84b5-352a3c6d4f10.png)

**Sources**

*no sources*

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20211208
 - compared it to version 20211004.1 

**Additional context**

on the older versions, for example the October update did not have any problem directing the vehicle to its destination with a slight miscalculated path at its first and corrects it after, and as far as I know this was not reported earlier on at the November updates and has been unfixed prior to the latest December update

**Comment by Waffle1434** [comment]
Fixed a few weeks ago for next release
