### ISSUE TITLE
You can drive over the invisible wall on test drive

### ISSUE THREAD

**Issue by concuexe** [RadianSimulations/ghpc-feedback#60]
When in test drive, it is possible to drive past and get stuck on the 1st invisible wall and in some cases even reach the 2nd invisible wall

To reproduce:
Go to test drive
Use either the T-55, T-72, BMP-1, BRDM-2 or M903
Drive into the wall stopping you from going into the firing range

Expected behavior
Wall stops you from entering the range

OS: Windows 10
Game version: up to 2022020
![2022-02-09T112621](https://user-images.githubusercontent.com/99333048/153199354-d477364f-400e-4858-b704-aaf80b6fd248.png)
![2022-02-09T112631](https://user-images.githubusercontent.com/99333048/153199373-a19f5d9c-d830-476e-9eeb-f258e216d014.png)
![2021-12-04T045113](https://user-images.githubusercontent.com/99333048/153199434-05427e30-02c3-4d83-9221-9c6f9c80f94c.png)

**Comment by JoshBusuito** [comment]
There is only one invisible wall, a couple of meters forward of the barrier line, and these vehicles are striking it.  The invisible wall is vertical, quite tall, and has never been crossed successfully by anyone to date.
