### ISSUE TITLE
Nighttime battle: completely black sky with daytime-brightness terrain

### ISSUE THREAD

**Issue by Spudicous** [RadianSimulations/ghpc-feedback#61]
Issue: Sky was completely black, more so than normal nighttime in the game, but the terrain was lit like it was daytime. The commander's view defaulted to nightvision and the IR spotlight covers on the T-72 were the only indication of what the time of day was 'supposed' to be. ',' and '.' had no noticeable effect on either the sky or the terrain, but I only tried them for a few seconds.

No other adverse effects were noticed.

![2022-02-13T045319](https://user-images.githubusercontent.com/92068308/153741270-aeaaed36-67e8-4ea5-bff6-568c11f1a47f.png)

**Comment by AlexisGommet** [comment]
Also happened to me, i don't if it was because i kept trying to use ',' and '.', but it went back to normal after a while.

**Comment by blake-bracerstudios** [comment]
There is a certain time that causes issues with our lighting shaders, and at this point we've removed the ability to change time to lessen this from happening.
