### ISSUE TITLE
M1IP's Ammo rack door's contributing to major performance drops after exiting gunner sight mode

### ISSUE THREAD

**Issue by Lotusen** [RadianSimulations/ghpc-feedback#62]
**Describe the bug**

one of the ammo rack blast doors is causing major fps drops after exiting the gunner sights during battle, what it does is lagging out of the tank/ clipping out of the tank and while doing so causes fps drops in a short time. I did an experiment one time on looking what does the door do when the bug happens and got to slow motion and surprisingly the severity of the door slowing down my pc drops as the door goes back to its intended spot like it is catching up from the tank

**To Reproduce**

1. Go to any playable missions that has the M1IP
2. go into the gunner sight after going reasonably fast
3. exit out of the sight
4. after so, you will see a door spazz/ lag out your tank

**Expected Behavior**

it should not clip out of the tank

**Screenshots**

no screenshots made due to how hard to catch it

**Sources**

no applicable sources

**Desktop (Please complete the following information):**

 - OS:  Windows 10
 - Game Version 20220206.1

**Additional context**
my pc specs:
 - GPU: RX 550
 - CPU: i3-9100F
 - RAM: 16 GB 2400 MHz
I don't know if it is because of poor PC performance that causes these

**Comment by JoshBusuito** [comment]
The door lagging out is a known issue and is a result, not a cause, of performance issues.
