### ISSUE TITLE
Indomitable Investigation: Mission waypoints cause the AI to take over player controlled vehicles

### ISSUE THREAD

**Issue by TeyKey1** [RadianSimulations/ghpc-feedback#70]
**Describe the bug**
Mission: Indomitable Investigation

Once the player crosses a mission waypoint marked on the map, the AI takes over the player controlled vehicle and attempts to drive it back to the starting position. This can only be overridden by pressing either of the movement-keys (WASD) after which the vehicle is fully under player control again.

This happens on all waypoints in the mission, regardless of the vehicle (Abrams/Bradley) and regardless of driving with cruise control or manually.

**To Reproduce**

1. Select and start the mission "Indomitable Investigation"
2. Drive either of the vehicles into the first waypoint marked on the map
3. Observe the abovementioned behavior

**Expected Behavior**

The AI does not take control over a player controlled vehicle.

**Screenshots**

Video:
https://user-images.githubusercontent.com/78312153/161622579-77dc84d3-ab38-4bb7-9f1a-6167277121ec.mp4

**Sources**

Not applicable.

**Desktop (Please complete the following information):**

 - OS: Windows 10 Pro Build 19043
 - Game Version 20220401.1

**Additional context**

None

**Comment by rossmum** [comment]
Have seen this same issue happen sometimes in generated missions.

**Comment by blake-bracerstudios** [comment]
Generated missions are now no longer present in the game, so this should no longer happen.
