### ISSUE TITLE
UAZ open door hitbox is mismatched from visual model

### ISSUE THREAD

**Issue by Flametz** [RadianSimulations/ghpc-feedback#71]
**Describe the bug**

THE UAZ's door (and possibly any other moving door/hatch models) does not match the visual model when the driver/any other crew member bail out of a vehicle. Shooting at where the door is leads to no hits as the actual hitbox can be found elsewhere

**To Reproduce**

1. Force crew to bail by disabling something important like an engine
2. Aim at door and shoot, no hit message shows up
3. Aim at space next to door and keep shooting until hit message pops up
4. You have now found where the hitbox is, which is not where the visual model is.

**Expected Behavior**

Hitbox should line up with visual model

**Screenshots**

"Hitting" the door but not actually hitting:
https://cdn.discordapp.com/attachments/640775424414318592/961833366133567558/unknown.png

"Missing" the door but actually hitting:
https://cdn.discordapp.com/attachments/640775424414318592/961833450762043392/unknown.png

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: [Windows 10]
 - Game Version [20220401.1]

**Additional context**

N/A

**Comment by blake-bracerstudios** [comment]
Should be fixed.
