### ISSUE TITLE
Spider web gunsight mechanical linkage from the Bradley detaches when the gun is elevated to its maximum angle

### ISSUE THREAD

**Issue by Lotusen** [RadianSimulations/ghpc-feedback#72]
**Describe the bug**

The spiderweb gunsight's mechanical linkage detaches when the main gun is elevated up high aiming at the sky causes the mechanical link to mismatch their position causing it to detach. 

**To Reproduce**

1. Go to Proving Grounds
2. Switch to Bradley
3. aim at the sky
4. See the link detach

**Expected Behavior**

The mechanical linkage for the spider web gunsight should not detach

**Screenshots**

![image](https://user-images.githubusercontent.com/93954888/162570478-a78ce158-af96-416c-b8e3-7d7e3db8e056.png)

**Sources**

No applicable sources

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 202220401.1

**Additional context**

**Comment by blake-bracerstudios** [comment]
Should be fixed at this time, and if it's not, isn't that important for us to go back to it for the moment.
