### ISSUE TITLE
Levitating road on Fulda terrain

### ISSUE THREAD

**Issue by rossmum** [RadianSimulations/ghpc-feedback#74]
There's a section of road in the southwest of the Fulda terrain that's floating up to a metre above terrain. I noticed when I accidentally slid off it with my tank.

**To reproduce:** go to the position shown in the first screenshot.

**Expected behaviour:** road follows terrain.

**Screenshots:** 

![image](https://user-images.githubusercontent.com/90238132/167521301-acfb60c8-a039-4c95-b5e1-2c156ac89c8a.png)
![image](https://user-images.githubusercontent.com/90238132/167521297-7e5dcc61-8d94-4c8a-863f-8d638672ed2e.png)
![image](https://user-images.githubusercontent.com/90238132/167521324-d039a112-f6ce-4bb3-b000-b48828e92474.png)

**Sys info:**

OS Win 10 Home 21H2
GHPC ver. 20220508

**Comment by JoshBusuito** [comment]
For future reference, this terrain is called Outskirts (they're all Fulda terrains) 😄
