### ISSUE TITLE
Bradley 25mm M792 (HEI-T) performs extremely poorly against BRDM-2

### ISSUE THREAD

**Issue by Richardguy97** [RadianSimulations/ghpc-feedback#76]
M792 ammunition cannot directly penetrate the hull or turret of the BRDM-2 from any angle or even with heavy amounts of saturation, requiring the use of limited M791 AP rounds or a TOW. It's actually possible to shoot HE rounds into the ground just below the BRDM and cause them to "frag" upwards into the extremely thin hull floor, but not direct hits.

**To Reproduce**

1. play any scenario where the m2 bradley fights against the BRDM-2
2. load M792 HEI-T
3. deplete ammunition without scoring any meaningful damage

**Expected Behavior**

The BRDM is described as having armor that is extremely thin, not much more than 14mm at its best and as little as 5-7mm on most of the hull (per wikipedia). The unrealistic behavior of the M792 HE on the Bradley forces the player to use very limited ammunition types best used on tanks/IFVs, when the BRDM is readily penetrable by .50 BMG ammunition.

The M792 round is described as being "capable against helicopters and lightly/unarmored vehicles" in US army marketing material as well as from ammunition manufacturers; it is described as having similar muzzle velocity to the SAPHEI-T PGU-32 round (which does have a different projectile, allowing it to penetrate 13mm of RHA, @ 30 degrees, 1km) yet the M792 appears to be totally ineffective against targets where the protection level is greater than 3-4mm RHA, making it effectively useless against any vehicle that isn't a truck in GHPC. 

**Sources**
https://www.gd-ots.com/munitions/medium-caliber-ammunition/25mm-mk2-mpt-sd/
https://www.globalsecurity.org/military/systems/munitions/m792.htm
https://www.alternatewars.com/BBOW/Weapons/AFV_Guns/OATK_25x137mm_Ammo.pdf

**Desktop (Please complete the following information):**

 - OS: [Windows 10]
 - Game Version [e.g. 20220508.1]

Thank you.

**Comment by JoshBusuito** [comment]
Information provided is not sufficient to establish a sufficiently specific penetration value, nor to indicate that the in-game performance is unrealistic.
