### ISSUE TITLE
Specific drive joystick inputs on a stationary tracked vehicle cause rapid gear shifting, and jittery vehicle movement

### ISSUE THREAD

**Issue by Whitey789** [RadianSimulations/ghpc-feedback#77]
**Describe the bug**

When in a stationary tracked vehicle, put your movement/drive joystick all the way *left/right*, and *very slightly* down. 
Vehicle will attempt to reverse and pivot on one track, as expected, but will instead *rapidly* switch between gears (1, 0, -1). 
Your vehicle will begin "jittering" or dancing. 

**To Reproduce**

1. Go to Proving grounds
2. Stay in the M60/Other tracked vehicle
3. Stay stationary
4. Put your drive joystick all the way left/right
5. Put the drive joystick *slightly* down, while holding left/right.
6. Vehicle should begin rapidly switching gears (1, 0, -1)

**Expected Behavior**

Vehicle should slowly pivot and reverse turn.

**Screenshots**

This a controller input needed to re-create this bug, [but shown via software.](https://i.gyazo.com/3997c1e6c71774465765bfedac39b723.png) This is a [gif of it happening](https://i.gyazo.com/262a79ae5ebfc190f49a318caec663a1.mp4), but the M60 is rotating notably faster in this than other vehicles when reproducing this bug.

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20220508.1

**Additional context**

Tested on two clients, both fresh installs, 1st time users.
Tested with a steam deck (via streaming) and an off-brand Xbox controller.
Most replicatable on M60, but happens with all tracked vehicles, underpowered is more visible.

**Comment by blake-bracerstudios** [comment]
Vehicle physics are very WIP and will have changes made to them through EA development. Closing this for now.
