### ISSUE TITLE
Lighting system is inconsistent

### ISSUE THREAD

**Issue by Lotusen** [RadianSimulations/ghpc-feedback#81]
**Describe the bug**

the shadows being casted by the cloud is not rendering properly and causing it to glitch on and off when looking into different angles but may sometimes show the shadow correctly on some specific degrees. There also inconsistencies on the lighting on the game and is prominent on the AAR yet I have not manipulated the time but as seen by picture below A, the sun is clearly aside the cloud and not being covered yet the surrounding area is casted on by an invisible cloud.

**To Reproduce**

1. Go to the third and last new mission "Kingly Kayak"
2. accelerate the time so that the sun is behind the cloud
3. You will see that nothing changed
4. play the game until it is finished
5. go to the After Action Report and cycle around the shots and you might be able to see the phenomenon when looking on different perspectives 
(this behavior is inconsistent but replicatable and applies to all maps)

**Expected Behavior**

It should properly display the cloud being casted on the area and not glitch on and off.

**Screenshots**
![Screenshot (242)](https://user-images.githubusercontent.com/93954888/178489846-0933188b-8348-444d-8204-ed89f4627500.png)
![Screenshot (241)](https://user-images.githubusercontent.com/93954888/178489862-ee7cab89-6b64-46f6-a410-3b5d77ed0a71.png)
https://user-images.githubusercontent.com/93954888/178489894-d3bc0a2e-b354-4957-9efc-78a22c9f2a38.mp4
https://user-images.githubusercontent.com/93954888/178489917-3b3e25be-e139-4db4-97ee-59af9226c94b.mp4
A:
![Screenshot (255)](https://user-images.githubusercontent.com/93954888/180610092-1feb582f-3d9d-443b-b9ed-d55b92da782a.png)
![Screenshot (254)](https://user-images.githubusercontent.com/93954888/180610096-3fa8e9c0-b737-43b0-ba07-c8c643becb57.png)
![Screenshot (256)](https://user-images.githubusercontent.com/93954888/180610779-8b5f445a-6089-474c-b821-10b05671416a.png)

**Sources**

_no applicable sources_

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20220711

**Additional context**

.

**Comment by blake-bracerstudios** [comment]
Lighting will change as the game takes more shape. Not really a bug.
