### ISSUE TITLE
Valley Push tank not firing on mission start 

### ISSUE THREAD

**Issue by MW6768** [RadianSimulations/ghpc-feedback#82]
**Describe the bug**
Starting tank not firing/ceasing mid fight
I’ve experienced this issue where the tank you spawn in will not fire it’s main gun. The breach is loaded and the crew is not loading or cycling new rounds nor is the tank damaged in any place that would hinder it’s ability to fire. There are times where the tank works as intended when the mission starts but the same issue as above will happen midway through the fight with no damage to the tank or crew and no rounds being cycled, loaded or changed. 
**To Reproduce**
This error seems to happen consistently. Managed to catch it 4 times in a row before the mission worked correctly again.   
1. Start mission. 

**Expected Behavior**

Expected the tank to function without issue so the mission can continue. 

**Screenshots**

I have a video clip that is attached at the bottom.  

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 10]
 - Game Version [e.g. 20210506.1]

**Additional context**

https://user-images.githubusercontent.com/109441980/179374782-a64ab539-6f0f-46e5-9c36-3b464c172539.MOV

**Comment by JoshBusuito** [comment]
The tank was "fire gated": the gun could not depress enough to meet the aim point.  On T-72 tanks with TPD-K1 gunsights, fire gating forces the red "ready to fire" disk at the top of the gunsight to turn off.  This will is the clue for the gunner that the tank is in an improper position to get the gun on target.  The solution is to move to a shallower slope or aim higher.
