### ISSUE TITLE
Ammo-racked turrets sometimes fall through the ground

### ISSUE THREAD

**Issue by CookiVibes** [RadianSimulations/ghpc-feedback#83]
**Description**
When a Russian MBT is ammo racked and the turret is shot up into the air, the turret can fall through the ground. This behavior is quite rare.

**Steps to reproduce the behavior:**

1. Shoot at an enemy tank
2. If the turret comes off, there's a small chance it'll clip through the ground

**Expected Behavior**

The turret shouldn't turn on noclip hacks and go to narnia. It should land on the ground!

**Screenshots**

![image](https://user-images.githubusercontent.com/109620456/179815590-cfe4e7d2-a06f-4761-881f-9609b64a872b.png)

**Desktop (Please complete the following information):**

 - OS: Windows 7
 - Game Version: 20220711

**Comment by blake-bracerstudios** [comment]
Turret skips a frame and falls through. Will address with a cleanup item later, but not high priority.
