### ISSUE TITLE
Commander and AI vehicles wallhack 

### ISSUE THREAD

**Issue by Galinjins** [RadianSimulations/ghpc-feedback#85]
On Fulda gap (north fields), mission ; kinetic key
Trees don't block vision of AI , my commander and a t55 was able to see my tanks and shoot a 1.9 km aways with 2 hills and a small forest blocking it's view , i was not able to see the t55 on thermal , after the start of the game i went to the trees on the little hill at the left just after spawn , then i headed on the road to the left heading to the village , the t55 was able to destoy my moving tank throught the trees and my commander was able to identify the tank, after 5 minutes i was able to kill the t55 (the files are too heavy so i put them on youtube)
i would guess the Ai don't take trees as "obstacles" in the code, or that the trees were not defined as obstacles when the map was created
https://www.youtube.com/watch?v=bkbB1H2O7sI
https://www.youtube.com/watch?v=vHC0yO6SMOU

**Comment by JoshBusuito** [comment]
Known issue, fixed in dev branch for next patch
