### ISSUE TITLE
T-72M on Jolly Joust mission drives in circles instead of advancing

### ISSUE THREAD

**Issue by StegiTheStego** [RadianSimulations/ghpc-feedback#86]
**Describe the bug**

On the Jolly Joust mission (one of the Fulda Outskirts missions where you play as a platoon of T-72M's and have to capture OBJ Anna, after which a second platoon wil advance towards OBJ Boris before splitting off to capture OBJ Vasily), after taking out the M113's, capturing objective Anna, and losing two T-72M's, I switched over to the platoon on the hill rather than the one down in the valley. When I went to advance on OBJ Boris, none of the AI teammates went with me, often spinning in place. I encountered this problem once when having captured OBJ Boris and looking at two AI T-72M's who drove in circles around each other. First time I encountered this problem I alt+tabbed to open OBS to record this, but my force got taken out. The second time I managed to record it, albeit with only one tank driving in circles.

**To Reproduce**

1. Go to the Jolly Joust mission under Fulda Gap - Fulda Outskirts
2. Capture OBJ Anna and advance to OBJ Boris
3. Watch the AI teammates on whether or not if they follow.

**Expected Behavior**

I expected the T-72M's to follow me to Objective Boris, as the mission description states they'll only break off once OBJ Boris has been captured.

**Screenshots**

No screenshots, but I included a video of the second time I saw the problem, and the first time I managed to record it.

P.S.: There's a PNG-tuber avatar in the recording because I forgot to turn it off (I stream the game sometimes)

**Sources**

None regarding Armor and Penetration, but mostly on helping fix the AI and having the tank company be focused on completing the objective and not goofing around.

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version: GHPC Patreon 20220711

https://user-images.githubusercontent.com/88275499/184190991-347f9f0f-c920-402b-9016-ca694120c784.mov

**Additional context**

None.

**Comment by JoshBusuito** [comment]
This is a well known issue not specifically related to any single mission or vehicle.
