### ISSUE TITLE
M2 Bradley Daysight Illumination

### ISSUE THREAD

**Issue by Dooby333** [RadianSimulations/ghpc-feedback#88]
**Describe the bug**

M2 Bradley daysight illumination toggle turns the lines for aiming ATGMS bright white, and can't be returned to their normal black color.

**To Reproduce**

1. Take command of an M2 Bradley
2. Look through the gunner's daytime sight
3. Press your sight illumination key to see the bug
4. Press it again to see that it can't be reversed and that it remains white.

**Expected Behavior**
I am unaware if the tow sight has an illumination setting in the daysight, and assume it should remain black, or change to a more usual sight illumination color like red  green or yellow if there is indeed an illumination setting.

**Desktop (Please complete the following information):**

 - OS: [Windows 10]
 - Game Version [20220822]

**Comment by ComradeCheekiBreeki** [comment]
I can confirm the same issue, pressing the "Daysight Illumination" key while in the Bradley's sights permanently changes the TOW crosshair to white.

**Comment by JoshBusuito** [comment]
Fixed by RadianSimulations/GHPC-vertical#1247
