### ISSUE TITLE
M1IP GAS reticle backlighting does not appear for HEAT reticle

### ISSUE THREAD

**Issue by rossmum** [RadianSimulations/ghpc-feedback#90]
**Describe the bug**

Pretty simple, the sabot GAS reticle is able to be backlit, the HEAT one is not.

**To Reproduce**

1. Get in the M1IP.
2. Switch to GAS and turn backlighting on. Select HEAT, fire the sabot round up the spout.
3. Observe lack of lighting as reticle changes.
4. Press the backlight button a few times, then switch back to sabot. The lighting will work again when the reticle switches.

**Expected Behavior**

Backlighting to be consistent between reticles (and to work for them both), like the M1.

**Desktop (Please complete the following information):**

 - OS: W10 Home 21H2
 - Game Version 20220822

**Additional context**

This problem only affects the M1IP. The backlighting on the OG M1 works as expected.

**Comment by JoshBusuito** [comment]
Fixed by RadianSimulations/GHPC-vertical#1249
