### ISSUE TITLE
Game crashes shortly after loading completes

### ISSUE THREAD

**Issue by jttune** [RadianSimulations/ghpc-feedback#93]
**Describe the bug**

Game crashes when loading completes, shortly after the vehicles spawn in. Game is sometimes playable for very short periods of time before crash occurs.

Crash Log:
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/9500465/Player.log)

**To Reproduce**

1. Start game
2. Click on "Instant" or start a new campaign
3. If instant mission is selected: click on Fun Drive
4. Wait for loading to complete
5. Use tab to select vehicle
6. Crash occurs
7. If new campaign is started: Select NATO and Recon in Force on upper left corner of the Fulda map
8. Wait for loading to complete
9. Crash occurs as soon as player and vehicle spawns in

**Expected Behavior**

Game does not crash

**Screenshots**

**Sources**

If applicable, cite any public confirmed sources needed to justify issues involving armor values and ammunition types.
Common concerns like "This doesn't feel right" or "_Other Game_ does it this way" are **not** valid citations and we will cause the issue to be removed.

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20220830 Steam Early Access

**Additional context**

Crash Log included below:
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/9500460/Player.log)

**Comment by blake-bracerstudios** [comment]
Alleviated some memory issues in recent releases. If the problem persists, repost.
