### ISSUE TITLE
Fire, smoke effects and internal modules bugged out. + PAUSING GAME STILL BREAKS SOUND

### ISSUE THREAD

**Issue by LilEkCZ** [RadianSimulations/ghpc-feedback#95]
After pausing the game and changing graphics, all fire and smoke effects started rotating around me as i was looking around in 3rd person view. They stayed at the same relative place to each other but were all completely disconnected from the rest of the map.

Some modules in the AAR were also floating out of place rotating as I was looking around.

+ Sound just stops if you pause in mission

**To Reproduce**
I wasn't able to reproduce the effect thing.

+
Go into any mission, press P to pause.
Game sound should stop.

**Expected Behavior**

Expected behavior is that effects stay locked to their proper place and don't rotate freely

Expected behavior is that sound resumes normally

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/85505970/188945264-3b93a0d2-dbfd-4fab-aed7-6b61eab753ff.png)
![Screenshot_2](https://user-images.githubusercontent.com/85505970/188945281-f7c9f090-6983-4056-8fd9-7e8691b2b01f.png)

![Screenshot_4](https://user-images.githubusercontent.com/85505970/188945369-28f90f53-8823-4322-bffc-1d79f41d7ca9.png)
![Screenshot_3](https://user-images.githubusercontent.com/85505970/188945389-b95592c4-4f28-4e3c-b1a4-735ae6316d69.png)

 - OS: [Windows 10]
 - Game Version [e.g. 20220830]

**Comment by blake-bracerstudios** [comment]
Several of these have been addressed and fixed by the time of 20221218 release.
