### ISSUE TITLE
T-55 ammo-racked/cooked-off turrets will still have the crew inside them

### ISSUE THREAD

**Issue by ComradeCheekiBreeki** [RadianSimulations/ghpc-feedback#96]
**Describe the bug**

When a T-55 turret cooks off after ammo-racking an enemy vehicle, sometimes the crew in the fighting compartment will not die and stay attached to the turret as it flies off, still able to take hits.

**To Reproduce**

1. Find an enemy T-55
2. Ammo rack it so its turret immediately cooks off
3. Fire above the turret (provided it landed upside-down) where the loader/gunner would be in relation to it if it were still attached to the tank
4. Watch the shot hit the nonexistent crew and give you reports of penetrating crew body parts

**Expected Behavior**

The obviously expected behavior would be for the crew to die upon ammo racking the vehicle and stay inside the main body, with the turret flying off by itself.

**Screenshots**

![image](https://user-images.githubusercontent.com/10621041/189462435-1fe4d91e-cbd7-479f-9999-3bb02172dc09.png)

This is a screenshot of a hit report from the AAR of the "Long Range" mission. As you can see, the shot hit the leg of the phantom loader, who appears to still be alive (along with the rest of his crew) based on how he is posed, before continuing on to my intended target. The turret is obviously unattached, having be cooked off from the BMP in the background which is missing a turret.

**Desktop:**

 - OS: Windows 10
 - Game Version: 20220830

**Additional context**

This has only happened to me with a T-55A, but it could also be a problem with other vehicles as well. It's not a massive issue as the crew will rarely ever stop shots from reaching their targets, but it could end up being quite annoying if crew data is ever tracked (i.e in a campaign) or as new vehicles get added. It's also very silly.

**Comment by JoshBusuito** [comment]
The crew do indeed die when catastrophic detonation occurs. Their representative models remaining in place in the turret mesh is essentially a cosmetic issue at that point. It may or may not ever be fixed.
