### ISSUE TITLE
Game Crash: Instant Action Map

### ISSUE THREAD

**Issue by gahopp** [RadianSimulations/ghpc-feedback#97]
**Describe the bug**

Game crashes entirely back to Desktop. Occurs halfway through playing Instant-->Fulda Gap, Fulda Outskirts--> Indomitable Investigation. Has happened three times all as clearing Phase Line 3

**To Reproduce**

1. Go to 'Instant-->Fulda Gap, Fulda Outskirts--> Indomitable Investigation
2. Clear Phase Line 2 and proceed to clearing Phase Line 3
3. Before reaching Phase Line 3 game locks and then crashes back to Desktop

**Expected Behavior**

Player clears all Phase Lines without game crashing

**Screenshots**

**Sources**

None

**Desktop (Please complete the following information):**

 - OS: [e.g. Windows 11 Home 21H2]
 - Game Version [e.g. 20220830] from Steam Download

**Additional context**

None.

**Comment by brikabrak** [comment]
Please attach your Player.log. Instructions on how to pull this are located on [our official discord](https://discord.gg/ghpc), pinned in the `testing-feedback` channel.

At the bottom of your Player.log, you'll find a path for your machine to locate a crash.dump file. It would be useful to provide that as well, but not necessary.

**Comment by gahopp** [comment]
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/9616725/Player.log)
apologize for the delay

**Comment by blake-bracerstudios** [comment]
I don't see a crash noted in this log, so if you played after the time you crashed, that log was blown away. After it crashes the next time, please find and attach your Player.log file here.

**Comment by blake-bracerstudios** [comment]
Closing this as it has become stale. If it persists, please recreate the issue.
