### ISSUE TITLE
AI is able to effectively engage at long range from behind concealment much faster than the player (and other related issues)

### ISSUE THREAD

**Issue by ComradeCheekiBreeki** [RadianSimulations/ghpc-feedback#98]
**Describe the bug**

The AI in general is quite inconsistent with the way they acquire and accurately hit targets. Sometimes they seem completely incapable of finding their assailant even if the shot path is very clear and unobstructed, whereas other times (as detailed in this post) they are superhumanly good at acquiring targets from absolutely bonkers ranges and hitting them with absurd accuracy even when their shot path is obstructed by foliage.

This issue seems to stem primarily from two things: one, the way in which the AI handles long distance engagements (there doesn't seem to be a penalty to aim time or accuracy at extreme ranges or forced manual bracketing or anything like that, just more difficulty in acquiring targets) and two: the way foliage obstructs (or rather, doesn't obstruct) AI line of sight.

**To Reproduce**

1. Load any map conducive to long range combat (for best results, forested areas that the player is attacking uphill are good at exacerbating this issue)
2. Engage with an enemy at long range (again, enemies behind forest cover will benefit the most from this)
3. After receiving shots, let the commander direct your turret towards the position of the enemy vehicle
4. Observe your effective acquisition of the target vs. how accurately you or your allies are being hit

**Expected Behavior**

The expected behavior would be that, for AI to fire accurately, those AI who put themselves into concealment would need to be very close to the edges of tree lines and be ahead of any other obstructions, meaning they usually could not be any further than one tree line or set of bushes back from their target. Additionally, AI shot ranging and accuracy behavior should be tied to the vehicle they are using (more than it already is, of course), factoring in laser range-finding capability, turret mobility, effective distance and things like that. The AI should be forced to bracket their shots significantly or simply not engage at ranges approaching or higher than their optic's effective range, especially considering how the player's distance fog makes them much harder to see at such extreme distances.

**Screenshots**

![image](https://user-images.githubusercontent.com/10621041/189506778-158c14e5-c03f-4a24-a404-c3f945c84908.png)
Above is a screenshot of a particularly ridiculous T-55A hit that I took, gauged at 2.5km. This T-55A made at least 5 solid (i.e wounding or killing) hits on me and my two allies, ammo racking me and another friendly. Out of the 25 hits in this mission, at least a third (and definitely more than half on the enemy side) were performed by this one tank. He also never moved the entire game, staying more or less in the same position, as all of hits show at least 2.5km distance.

![image](https://user-images.githubusercontent.com/10621041/189506856-9c3d9641-3be4-436f-919e-cf0d6e7828b1.png)
![image](https://user-images.githubusercontent.com/10621041/189506860-48032b06-2959-4191-a296-92ec6d2bb94f.png)
![image](https://user-images.githubusercontent.com/10621041/189506864-def992a5-2946-4cf3-928c-ee82cb55c97b.png)
These images are the commander-aimed view of all three of my friendly tanks. Obviously the conditions were not ideal on my end, but this is against a tank that has a maximum optical range of 2km and no laser rangefinder. I did not see any discernable part of the enemy tank the entire game, and I spent more or less the entire game looking down this single sight line to find him.

![image](https://user-images.githubusercontent.com/10621041/189506952-2324047c-ca7d-42ac-a15f-347df282833f.png)
And here is a view of about half of the shot path, with my position being somewhere in the blue circle. The red circles are areas that made it hard or impossible for me to see the enemy, and I think consequently should've made it impossible for him to accurately hit, let alone acquire, me.

**Sources**

(The following covers specifically the T-55A as it is the vehicle I encountered the most egregious example of, though I have had it happen with T-72s as well)
There seems to be a fairly common assertation that the maximum range of the T-55's optics (including laser rangefinder) is about 1km-2km, with its effective range during the day being 800m-1km. I could find multiple fact sheets on the T-55 (See [here](https://man.fas.org/dod-101/sys/land/row/t54tank.htm) and [here](https://www.globalsecurity.org/military/world/russia/t-54-specs.htm)) that say its effective range was within this margin, though they are not necessarily reliable sources and do not source anything themselves so they should be taken with a grain of salt. While it would make sense for this range to be extended more in game to compensate for the "squishing" that goes into creating realistic environments in games, 2.5km is still exceptionally high to even be able to reasonably acquire an enemy vehicle at, let alone consistently hit shots from with a tank that features no laser rangefinder.

Also, while the T-55A's sight does feature range markings for distances much further than 1-2km, they are intended for indirect fire and not directly engaging with enemy armor at those distances due to the aforementioned maximum optical range.

**Desktop:**

 - OS: Windows 10
 - Game Version 20220830

**Additional context**

I want to stress that this is not a fluke, and I have had this similar situation play out many times. Most of the time it's a small annoyance, since it may be one tank that I can easily flank with the help of my platoon after losing one or two friendly assets, but in a situation like this, where we were already outnumbered and being forced to stick together, it was particularly noticeable and spurred me to record it.

I also don't want this to sound like me raging about dying while out of position- I want to make no excuses for my play this match as I certainly could've made better use of terrain cover. But I can't help but feel a little bit cheated to die in this kind of way. I understand that it is very hard to walk the line between braindead AI and AI easily capable of outperforming the player in every way, but I feel like there must be a better solution to stop situations like this from happening.

**Comment by just1inmany** [comment]
Yeah this has been happening with all forces, TOWs, Bradleys, M1's, T-55's. On defense I can basically win any defense mission by parking a platoon of tanks in the center of an elevated forest then switch to a scout like a BRDM, and the T-55's (or any tank really) will shoot through the trees and wipe out all enemies without terrain blocking them.

**Comment by blake-bracerstudios** [comment]
This is less of a bug and more of a game balancing issue, which will be addressed as we do our development. Closing now to clear the backlog. Thanks for the feedback.
